console.log('extension script loaded')
//values for parsing vendor products into each of the modal fields
const category = [
    "Achillea",
    "Agapanthus",
    "Alstroemeria",
    "Amaranthus",
    "Amaryllis",
    "Anemone",
    "Artichoke",
    "Aster",
    "Astilbe",
    "Astrantia",
    "Ball Mum",
    "Bells Of Ireland",
    "Birds of Paradise",
    "Brilliantina",
    "Bupleurum",
    "Calla",
    "Campanula",
    "Carnation",
    "Carthamus",
    "Celosia",
    "Craspedia",
    "Cremon",
    "Dahlia",
    "Delphinium",
    "Dianthus",
    "Dubium",
    "Dusty Miller",
    "Eryngium",
    "Eucalyptus",
    "Feverfew",
    "Football Mum",
    "Freesia",
    "Garden Rose",
    "Garden Rose David Austin",
    "Garden Spray Rose",
    "Gerbera",
    "Gladiolas",
    "Godetia",
    "Gypsophila",
    "Hyacinth",
    "Hydrangea",
    "Hypericum",
    "Iris",
    "Kale",
    "Kangaroo Paw",
    "Large Callas",
    "Larkspur",
    "Leatherleaf",
    "Lepidium",
    "Leucadendron",
    "Leucospermum",
    "Liatris",
    "Lily Asiatic",
    "Lily L.A",
    "Lily Oriental",
    "Limonium",
    "Lisianthus",
    "Lysimachia",
    "Marigold",
    "Matricaria",
    "Mini Calla",
    "Mini Carnation",
    "Monkey Tail",
    "Nigella",
    "Ornithogalum",
    "Pampas Grass",
    "Pennycress",
    "Peony",
    "Phlox",
    "Photinia",
    "Pomp Assorted",
    "Pomp Button",
    "Pomp Cushion",
    "Pomp Daisy",
    "Pomp Novelty",
    "Poppies",
    "Protea",
    "Ptilotus",
    "Queen Anne's Lace",
    "Raffine",
    "Ranunculus",
    "Riceflower",
    "Rose",
    "Ruscus",
    "Safflower",
    "Scabiosa",
    "Snapdragon",
    "Spider Mum",
    "Spray Rose",
    "Star of Bethlehem",
    "Statice",
    "Stock",
    "Strawflower",
    "Succulent",
    "Sunflower",
    "Sweet Pea",
    "Tulips",
    "Tweedia",
    "Veronica",
    "Veronica Spray",
    "Waxflower"
];
const color = [
    "Antique Peach",
    "Antique Pink",
    "Antique Green",
    "Assorted",
    "Bicolor Green/Pink",
    "Bicolor Orange",
    "Bicolor Orange/Pink",
    "Bicolor Pink",
    "Bicolor Pink/Orange",
    "Bicolor Purple",
    "Bicolor Purple/Cream",
    "Bicolor Red/Pink",
    "Bicolor Red/White",
    "Bicolor White/Pink",
    "Bicolor White/Red",
    "Bicolor Yellow/Red",
    "Bicolor Yellow/White",
    "Bleached",
    "Blue",
    "Bronze",
    "Brown",
    "Burgundy",
    "Caramel",
    "Champaign",
    "Coral",
    "Dark Blue",
    "Dark Burgundy",
    "Dark Green",
    "Dark Orange",
    "Dark Red",
    "Easter Assorted",
    "Fall Assorted",
    "Green",
    "Hot Pink",
    "Lavender",
    "Light Pink",
    "Light Red",
    "Mother's Day Assorted",
    "Novelty Assorted",
    "Orange",
    "Patriotic Tinted",
    "Peach",
    "Pink",
    "Pink Assorted",
    "Purple",
    "Red",
    "Sandy",
    "Silver",
    "Spring Assorted",
    "St Patricks' Assorted",
    "Tessino Assorted",
    "Tinted Assorted",
    "Tinted Rainbow",
    "Tinted Black",
    "Tinted Blue",
    "Tinted Bronze",
    "Tinted Brown",
    "Tinted Fall Assorted",
    "Tinted Glitter Assorted",
    "Tinted Green",
    "Tinted Green.",
    "Tinted Lavender",
    "Tinted Light Pink",
    "Tinted Orange",
    "Tinted Purple",
    "Tinted Rainbow",
    "Tinted Red",
    "Tinted Silver",
    "Tinted Spring Assorted",
    "Tinted Turqoise",
    "Tinted White",
    "Tinted Xmas Pack",
    "Valentine's Day Assorted",
    "Variegated Pink",
    "White",
    "Xmas Assorted",
    "Xmas Tinted Assorted",
    "Xmas Tinted Glitter Assorted",
    "Yellow"    
];
const grade = [
    "100 /120cm",
    "100/110cm",
    "100/120cm",
    "1000 Grams",
    "100cm",
    "110/120cm",
    "110cm",
    "120/200cm",
    "120cm",
    "130/140cm",
    "130cm",
    "140cm",
    "150 Grams",
    "150cm",
    "160cm",
    "180cm",
    "1Ft",
    "1Ft  /1 1/2Ft/ 2Ft",
    "2 Blooms",
    "2/3 Blooms",
    "200 Grams",
    "200cm",
    "20cm",
    "22/24",
    "22/28",
    "25/30cm",
    "25/35cm",
    "25/40cm",
    "25/45cm",
    "250 Grams",
    "25cm",
    "280 Grams",
    "280 Grams ",
    "2Ft",
    "2Lb",
    "3 Bloom",
    "3 Blooms",
    "3 Blooms +",
    "3/4Ft",
    "3/5 Blooms",
    "30/35cm",
    "30/40cm",
    "30/40cm",
    "30/45cm",
    "30/50cm",
    "300 Grams",
    "30cm",
    "320 Grams 30cm",
    "320 Grams 40cm",
    "320 Grams 45/50cm",
    "320 Grams 45cm",
    "320 Grams 50/55cm",
    "320 Grams 50/60cm",
    "320 Grams 50cm",
    "320 Grams 55/60cm",
    "320 Grams 55cm",
    "320 Grams 60/70cm",
    "320 Grams 60cm",
    "320 Grams 65cm",
    "320 Grams 70cm",
    "320 Grams 75cm",
    "320 Grams 80cm",
    "320 Grms",
    "35/40cm",
    "35/45cm",
    "35/50cm",
    "35/55cm",
    "35/60cm",
    "35cm",
    "35cm ",
    "3Ft",
    "40/45",
    "40/45cm",
    "40/45cm",
    "40/50cm",
    "40/50cm",
    "40/50cm",
    "40/50cm",
    "40/55cm",
    "40/55cm ",
    "40/60cm",
    "40/70cm",
    "40+cm",
    "40cm",
    "40cm ",
    "40cm/50cm",
    "40cm/50cmcm",
    "40cm/50cmcm",
    "40cm/60cm",
    "425Grams",
    "45/50cm",
    "45/55cm",
    "45/60cm",
    "45cm",
    "45cm ",
    "45cm  ",
    "5 Blooms",
    "50/55cm",
    "50/60cm",
    "50/60cm",
    "50/60cm",
    "50/70",
    "50/70cm",
    "50/80cm",
    "50cm",
    "50cm ",
    "50cm/60cm",
    "60cm/70cm",
    "70cm/80cm",
    "50cm/60cmcm",
    "50cm/60cm",
    "50cm/70cm",
    "52/65cm",
    "52cm",
    "55/60cm",
    "55/65cm",
    "55/70cm",
    "55cm",
    "60/65cm",
    "60/70cm",
    "70/80cm",
    "60/70cm",
    "60/80cm",
    "60/90cm",
    "60cm",
    "60cm ",
    "60cm 3/5 Blooms",
    "60cm/70cm",
    "60cm/70cm",
    "65/70cm",
    "65cm",
    "7/8cm",
    "70/100cm",
    "70/75cm",
    "70/79cm",
    "70/80cm",
    "70/80cm",
    "70/80cm ",
    "70/90cm",
    "70cm",
    "70cm ",
    "70cm/80cm",
    "750 Grams",
    "75cm",
    "80/100cm",
    "80/89cm",
    "80/90cm",
    "80cm",
    "85/90cm",
    "85cm",
    "90/100cm",
    "90/110cm",
    "90cm",
    "90cm 3Ft",
    "95cm",
    "Double",
    "Extra",
    "Extra Large",
    "Extra/Mini",
    "Fancy",
    "Giant",
    "Jumbo",
    "Jumbo 100cm +",
    "Large",
    "Large 60cm",
    "Large 8/10cm",
    "Large/Petite",
    "Long",
    "Medium",
    "Mini",
    "Mini 40/60cm",
    "Perfection",
    "Petite",
    "Petite 3/5cm",
    "Platinum",
    "Premium",
    "Premium 80cm",
    "Regular",
    "Select",
    "Short",
    "Small",
    "Standard",
    "Super Extra",
    "Super Premium",
    "Super Select",
    "Tall",
    "Tips",
    "Tips 12Ft",
    "Tips 25Lbs",
    "Tips 3Ft",
    "Tips 6Ft",
    "X/Large",
    "X/Large 15/20cm"
    
]
const variety = [
"Aalsmer Gold",
"Aaron",
"Aazur",
"Aazur Bordeaux",
"Abanico",
"Abratanoides",
"Absinthe",
"Absolute In Pink",
"Absurda",
"Acapulco",
"Accent",
"Ace",
"Acqua Sun Birds",
"Act Rima",
"Act Zara",
"Acuarela",
"Acuarella",
"Adele",
"Adream",
"Adria",
"Adrissa",
"Affogato",
"Afogatto",
"African Agathosma",
"Afrodita",
"Agate",
"Agavoides",
"Agnese",
"Aisha",
"Aiti",
"Akari",
"Akito",
"Aktiva",
"Alaba",
"Alabaster",
"Alana",
"Alaska",
"Alba",
"Albareto",
"Albino",
"Albufeira",
"Aldia",
"Alegria",
"Alejandra",
"Alemani",
"Alero",
"Alero Apricot",
"Alert",
"Alertie",
"Alessia",
"Alex",
"Alexander Fleming",
"Alexis",
"Alhambra",
"Alibaba",
"Alice",
"Alicia",
"Alien",
"Aline",
"Alis",
"Alive",
"Aljonka",
"All By Myself",
"All For Love",
"All Of Me",
"Alligator",
"Allspice",
"Allure",
"Alma",
"Alma Ata",
"Almendra",
"Almendra Solkiss",
"Almond",
"Aloha",
"Alondra Blue Dutch",
"Alondra Rose Dutch",
"Alpinia Purpurata/Ginger",
"Alpinia Zerumbet",
"Alpino",
"Alpinum Blue",
"Alquimia",
"Altamira",
"Aly",
"Alyna",
"Amandine",
"Amandine Barbie",
"Amandine Black",
"Amandine Chamalow",
"Amandine Gold",
"Amandine Marshmallow",
"Amandine Pastel",
"Amandine Pauline Violet",
"Amandine Porcelain",
"Amandine Shehe",
"Amandine White",
"Amandinne Tango",
"Amaretto",
"Amarossi",
"Amaru",
"Amateras",
"Amatista",
"Amazane",
"Amaze",
"Amazon",
"Amazon Cherry",
"Amazon Lavender Magic",
"Amazon Neon Cherry",
"Amazon Neon Purple",
"Amazon Purple",
"Amazon Rose Magic",
"Amazone",
"Amazone Dark",
"Ambar",
"Amber",
"Amber Syrup",
"Ambiance",
"Amelia",
"American Beech",
"American Dream Collection",
"Amethyst",
"Amethyst Dark",
"Ametrine",
"Amico",
"Amico Crimson",
"Amnesia",
"Amor Amarillo",
"Amor Candy",
"Amor Carmesi",
"Amor Flickers",
"Amor Joven",
"Amorosa",
"Amposta",
"Amsterdam",
"Amy",
"Ana",
"Anarosa",
"Anastasia",
"Andina",
"Andrea",
"Andrea Folies",
"Andrea Red",
"Anethum Dill",
"Angel",
"Angel Cheeks",
"Angel Tears",
"Angela",
"Angelina",
"Angels",
"Angel'S Pillow",
"Angie",
"Angie Romantica",
"Anklet",
"Anna",
"Annais",
"Annecy",
"Annice",
"Annie Schilder Single",
"Anouska",
"Antaris",
"Anthurium",
"Anthurium Calisto",
"Anthurium Choco",
"Antigua",
"Antike",
"Antique",
"Antique Green",
"Antique Mauve",
"Apetit",
"Aphrodite",
"Apollo",
"Appetit",
"Applause",
"Apple Serviceberry",
"Apple Tea",
"Apricot",
"Apricot Fudge",
"Apricot Picnic",
"Apricot Swirl",
"Apricott Alero",
"April",
"Apsu",
"Aqua",
"Aquamarine",
"Aquarel",
"Aquarella",
"Aquarelle",
"Arabian",
"Arabian Dawn",
"Arabic",
"Arabicum",
"Arabigo",
"Aragon",
"Aralia",
"Aralia Assorted",
"Aralia Leaves",
"Aranal",
"Arbatax",
"Arcachon",
"Arctica",
"Areka Palm",
"Arena",
"Arendelle",
"Arenita",
"Aretha",
"Ariel",
"Arizona",
"Arlecchino",
"Arleen",
"Arleene",
"Armonia",
"Arno",
"Arrow Folies",
"Arsenal",
"Art Deco",
"Artemis",
"Arthur Rimbaud",
"Artic",
"Artic Ice",
"Artic King",
"Artic Queen",
"Artica",
"Arusha",
"Ascot",
"Ash Plum",
"Ashes",
"Ashley",
"Ashley Spirit",
"Ashley White",
"Aspalanthus",
"Asparagus Plumoso",
"Aspen",
"Aspidistra",
"Aspidistra Green",
"Aspidistra Milkyway",
"Aspidistra Variegated",
"Asterian",
"Astolat",
"Astroid",
"Atacama",
"Athos",
"Atlantis",
"Atomic",
"Atriplex",
"Attache",
"Attraction",
"Auckland",
"Audabe",
"Augusta Luise",
"Aussie Mix",
"Austin",
"Autumn Breeze Blossom",
"Autumn Laurel",
"Autumn Vibes",
"Avalanche",
"Avalange",
"Avant Garde",
"Avanti",
"Avatar",
"Avianna",
"Avila",
"Ayoba",
"Azafran",
"Azahara",
"Azure",
"Azurite",
"B Bubbles",
"Babaloo",
"Babalu",
"Babe",
"Baby Blue",
"Baby Pink",
"Baby Rosever",
"Babylon",
"Bacarat",
"Bacarat Purple",
"Bacardi",
"Bach",
"Bachata",
"Bagpipe",
"Baileys",
"Balakov",
"Balance",
"Balboa Blue Picote",
"Bald Cypress",
"Bali",
"Bali!",
"Ballet",
"Ballett",
"Balsas",
"Baltazar",
"Baltica",
"Baly",
"Banana",
"Banana Pudding",
"Bandanas & Blooms Country Blue 9 Stem",
"Banksia Coccine",
"Barbados",
"Barbatus",
"Barbatus Arsenal",
"Barbatus Kiwi Boom",
"Barbatus Kiwi Bunny",
"Barbatus Leeds",
"Barbatus New Castle",
"Barberatus 2017 Msc 3",
"Barberatus 2017 Msfg 6",
"Barberatus Burgundy",
"Barberatus Cherry",
"Barberatus Fancy Burgundy",
"Barberatus Fancy White",
"Barberatus Iris",
"Barinton",
"Barista",
"Bariton",
"Barker Busch 400Gr",
"Baroness",
"Baronesse",
"Bartoli",
"Bartolini",
"Baru",
"Barullo",
"Bashful",
"Batavus",
"Batistero",
"Batman",
"Baya",
"Bayola",
"Be Charming",
"Be Generous",
"Be Gentle",
"Be Kind",
"Be Loving",
"Be Mine",
"Be Mine Bouquet 12 Stem",
"Be Patient",
"Be Romantic",
"Be Romantique",
"Be Sweet",
"Be True",
"Bear Grass",
"Beatrice",
"Beau Regarde",
"Beau Solei",
"Beau Soleil",
"Beaujolais Bouquet 10 Stem",
"Beauty By Oger",
"Becky",
"Beetle",
"Belen",
"Belen Star",
"Belgravia",
"Believe In Pink",
"Bell",
"Bell Of Ireland",
"Bell Pearl",
"Bella Donna",
"Bella Honey",
"Bella Sensation",
"Bella Star",
"Belladona Trick",
"Belladona Trick Ks",
"Belladona Trick Pink",
"Belladona Trick Yellow",
"Belladonna",
"Bellalinda",
"Bellalinda Brick",
"Bellalinda Cerise",
"Bellalinda Chic",
"Bellalinda Collection",
"Bellalinda Cream",
"Bellalinda Fucsia",
"Bellalinda Glee",
"Bellalinda Glee Coral",
"Bellalinda Kiss",
"Bellalinda Metallic",
"Bellalinda Pink",
"Bellalinda White",
"Bellavista",
"Belle Epoque",
"Bellevue",
"Bellina Collection",
"Bellisima",
"Bellissima",
"Bells",
"Bells Of Ireland",
"Bellville",
"Beloved",
"Bengala",
"Bernal",
"Bernard",
"Bernini",
"Berry",
"Berry Bunch",
"Besos Sun Birds",
"Bessie",
"Best Man",
"Besweet",
"Betsy",
"Bianca",
"Bianco Sfumato",
"Bianco Striato",
"Bicolor Mix",
"Big Bang",
"Big Ben",
"Big Ben Deep Blue",
"Big Ben Lavander",
"Big Ben Pink Imp",
"Big Ben White",
"Big Ben White Imp",
"Big Fun",
"Bikini",
"Bimba",
"Birba",
"Birch Tree",
"Bird Of Paradise Leaves",
"Bird Paradise",
"Birds And Berries",
"Birmania",
"Bis",
"Bizet",
"Black",
"Black Baccara",
"Black Beauty",
"Black Berry",
"Black Center",
"Black Cherry",
"Black Diamond",
"Black Eyed Beauty",
"Black Jack",
"Black Magic",
"Black Out",
"Black Spider",
"Black Star",
"Blackberry Focal Scoop",
"Blackberry Scoop",
"Blackberry Summer Scoop",
"Blanca",
"Blanche Spray",
"Blanquita",
"Blaze",
"Bleached",
"Blessing",
"Bling Bling",
"Bliss Cerisse",
"Bliss Storm",
"Blizzard",
"Bloody Mary",
"Blooming Love Premium 12 Stem",
"Blossom",
"Blossom Dark",
"Blue",
"Blue / Hot Pink",
"Blue Bell",
"Blue Belle Sun Birds",
"Blue Bird",
"Blue Copernico",
"Blue Curiosa",
"Blue Dream",
"Blue Glitter",
"Blue Ice",
"Blue Impulse",
"Blue Jackpot",
"Blue Lace White",
"Blue Lagoon",
"Blue Magic",
"Blue Manhattan",
"Blue Mistletoe",
"Blue Monster",
"Blue Moon",
"Blue Sapphire",
"Blue Stream",
"Blue Tips",
"Blue/White",
"Blueberry",
"Blueberry Mousse",
"Blue-Dynamite",
"Bluez",
"Bluocean",
"Bluocean - Coral",
"Bluocean - Jade",
"Bluocean - Opal",
"Bluocean - Purple Sapphire",
"Bluocean - Sapphire",
"Blush",
"Blushin' Ohara",
"Blushing Akito",
"Blushing Belle",
"Blushing Bride",
"Blushing Lady",
"Blushing Majolika",
"Boardwalk",
"Bochica",
"Bodega",
"Bogart",
"Bogdana",
"Boheme",
"Bohemian Bouquet",
"Bolero Pompomni",
"Bom Dye Gold",
"Bombay",
"Bombellini",
"Bomber",
"Bon Bon Focal Scoop French Vanilla",
"Bonanza",
"Bonfire",
"Bonita",
"Bonita Pink",
"Bonita Rose",
"Bonita White",
"Bora Bora!",
"Bordeaux",
"Borja",
"Born Free",
"Bosanska",
"Botani",
"Bottle Brush",
"Boulevard",
"Bounty Way",
"Bouquet",
"Bouquet 5 St + Leaf",
"Bouquets",
"Bouzeron",
"Bowl",
"Bowl Of Cream",
"Box A",
"Box B",
"Box C",
"Box D",
"Box Of Crayons",
"Boyfriend",
"Bqt",
"Bqt Mojito",
"Bradford",
"Brahama",
"Brahma",
"Braidth",
"Brasil",
"Brasilia",
"Braunni",
"Brave",
"Brazil",
"Brazilian",
"Brazuca",
"Brazuca Salmon",
"Break Out",
"Breanthus",
"Breanthus Amras",
"Breanthus Aston Villa",
"Breanthus Fingon",
"Breanthus Hera",
"Breanthus Jolly",
"Breanthus King",
"Breanthus Lindo",
"Breanthus Lord",
"Breanthus Melian",
"Breanthus Noble",
"Breanthus Prince",
"Breanthus Queen",
"Breathless",
"Breezer",
"Brenda",
"Bridal Akito",
"Bridal Pearl",
"Bridal Piano",
"Bridal Queen",
"Bridal Shower",
"Bridal Tiara",
"Bride",
"Bridesmaid",
"Bright Diamond",
"Bright Sensation",
"Brighton",
"Brillant Aries",
"Brillantina",
"Brilliant Star",
"Brilliant Stars Orange",
"Brilliant Stars Yellow",
"Brillianthus",
"Brillianthus Picote Blue",
"Brillianthus Picote Pink",
"Brindisi",
"Broad Leaf",
"Broad Street Metallic Rose 3 Stem",
"Brocoli",
"Bromeliad Paloma",
"Bromo",
"Bronze",
"Bronze Managua",
"Bronze Thrill",
"Brook",
"Brooks",
"Brownie",
"Bruja",
"Brunello",
"Brunia",
"Brunia Albiflora",
"Brunia Laevis",
"Brusago",
"Brut",
"Bubblegum Focal Scoop",
"Bubblicius",
"Buble",
"Budapest",
"Bugs Bunny",
"Bullit",
"Bumble Bee",
"Bumble Blee",
"Bumblebee",
"Bumblee Bee",
"Bunny Hug",
"Bunny Kisses",
"Bupleurum",
"Burgundy Pix",
"Butter",
"Butterfly",
"Butterfly Ariadne",
"Butterfly Artemis",
"Butterfly Charis",
"Butterfly Dione",
"Butterfly Eris",
"Butterfly Europa",
"Butterfly Grace",
"Butterfly Hades",
"Butterfly Helios",
"Butterfly Hera",
"Butterfly Isis",
"Butterfly Litai",
"Butterfly Lycia",
"Butterfly Magical Caramel",
"Butterfly Magical Ciocolato",
"Butterfly Magical Salmon",
"Butterfly Mascarpone",
"Butterfly Melissa",
"Butterfly Minoah",
"Butterfly Mix",
"Butterfly Musa",
"Butterfly Phytalos",
"Butterfly Rococoo",
"Butterfly Sensation Spray",
"Butterfly Theseus",
"Butterfly Thiva",
"Butterscotch",
"Buttery Blush",
"Button",
"C. Intermezzo",
"Cabaret",
"Cacao Theobroma",
"Cadbury Creme Eggs",
"Cadbury Eggs",
"Cadillac",
"Caers Palace",
"Caesar",
"Caesars Palace",
"Caezar",
"Cafe Au Lait",
"Cafe Au Lait Hybrid",
"Cafe Del Mar",
"Café Del Mar",
"Cafe Latte",
"Caffe D'Orzo",
"Caffe Latto",
"Cairo",
"Caitlyn",
"Calathea Leaf",
"Calathea Leaves White Star",
"California",
"California Red",
"Calima Yellow",
"Calime Pure White",
"Calipso",
"Calixta",
"Callista",
"Caluroso",
"Calypso",
"Camaleon",
"Camaro",
"Camel",
"Camel Fawn",
"Campanella",
"Campari",
"Camu Carl",
"Can Can",
"Canary",
"Canberra",
"Candela",
"Candid",
"Candie Light",
"Candied Yams",
"Candle",
"Candlelight",
"Candor",
"Candy",
"Candy Apple",
"Candy Apple Bubble Gum",
"Candy Bracelet Rainbow",
"Candy Cane",
"Candy Corn",
"Candy Flow Spray",
"Candy Focal Scoop",
"Candy Light Pink",
"Candy Mix",
"Candy Pck",
"Candy Scent",
"Candy Scoop",
"Candy Xpression",
"Canela",
"Canenza",
"Cannes Orange Iii",
"Cannes Yellow Iii",
"Cantor",
"Canyon",
"Caobo",
"Cap",
"Capability",
"Capadoccia",
"Cape Flora",
"Cappuccino",
"Capriccio",
"Capricho",
"Captain Cheerio",
"Captain Fresco",
"Captain Hollywood",
"Captain Kloon",
"Captain Melrose",
"Captain Paco",
"Captain Prado",
"Captain Promise",
"Captain Reno",
"Captain Romance",
"Captain Rosette",
"Captain Trinity",
"Captain Ventura",
"Capuccino",
"Capulus",
"Carabella",
"Caralinda",
"Caraluna",
"Caramel",
"Caramel Antike",
"Caramel Macchiato",
"Caramel Piaget",
"Caramelito Orange",
"Caramelo",
"Cardamon",
"Cardenal",
"Careless Whisper",
"Carey",
"Caribbean",
"Caribbean Sunsets",
"Caribean",
"Carlton",
"Carmela",
"Carmin",
"Carmine",
"Carnation Seasonal Bulk",
"Carnelian",
"Carnival",
"Carnival Arabian Dawn",
"Carnival Blue Bell",
"Carnival Cappuccino",
"Carnival Double",
"Carnival Duplo",
"Carnival Petite",
"Carnivora",
"Carnivore",
"Carol",
"Carole",
"Caroline",
"Caroline Gold",
"Caronte",
"Carpaccio",
"Carpe Diem",
"Carrot",
"Carrot Cheesecake",
"Carrousel",
"Cartagena",
"Carthamus",
"Cartier",
"Carzy Horse",
"Casa Blanca",
"Casablanca",
"Cascade Calla Bouquet",
"Casper",
"Cassy",
"Castellani",
"Catalina",
"Cataractarum Palm",
"Caterina",
"Catharina Fontijn",
"Catleya",
"Catone",
"Cavalese",
"Cavalesse",
"Cavalia",
"Cavallini",
"Cavendish",
"Cayenne",
"Cb",
"Cb 10St",
"Cb 2St Safari 1St Pincushion",
"Cb 3St",
"Cb Antique",
"Cb Cataractarum Palm 3 Stem",
"Cb Patriotic",
"Cb Pincushion",
"Cb Pincushion 1St",
"Cb Vday # 9",
"Cdn Bronze",
"Cdn Lavender",
"Cdn White",
"Ceb Dazzle",
"Cedar Blue Berry",
"Celebrate",
"Celebrated",
"Celest",
"Celestial",
"Celevenue",
"Celina",
"Celine Classic",
"Celtic",
"Center Ab Black",
"Central",
"Cereza",
"Cerinza",
"Cervantes",
"Cesar",
"C'Est La Vie",
"Cevennes",
"Cezanne",
"Chablis",
"Chamaleleon",
"Champagne",
"Champagne Bouquet 11 Stem",
"Champagnier",
"Champion Blue",
"Champion Pink",
"Champion White",
"Chanter Antique Rose",
"Chanter Pink",
"Chanter Red",
"Chanter White",
"Chanter Yellow",
"Chapeau",
"Chapeu",
"Charity",
"Charlie",
"Charlotte",
"Charm",
"Charm Combo Box",
"Charmant Collection",
"Charmant Large Petal",
"Charme Noir",
"Charming Corneille",
"Charming Irischka",
"Charming Irishka",
"Charming Unique",
"Charms",
"Chateau",
"Checkmate",
"Cheddar",
"Cheerio",
"Cheesecake",
"Chelo",
"Chelsea",
"Chelsea White",
"Cherio",
"Cherish",
"Cherrio",
"Cherry",
"Cherry Bay",
"Cherry Brandy",
"Cherry Folies",
"Cherry Love",
"Cherry O",
"Cherry O!",
"Cherry Tessino",
"Cherry Vanilla Focal Scoop",
"Cherry Vanilla Scoop",
"Cherry Violet",
"Cheryl",
"Chess",
"Chestnut",
"Chic Rose Bouquet",
"Chicago",
"Chicago River",
"Chili Pepper",
"Chilis",
"Chill Out",
"Chillis",
"Chispa",
"Chita",
"Chivas",
"Chivas Dark",
"Chocolate",
"Chocolate Lace",
"Chocolatta",
"Chopin",
"Chorus",
"Christa",
"Christmas #115",
"Christmas Bulb",
"Christmas Carol",
"Christmas Collection",
"Christmas Combo",
"Christmas Confetti",
"Christmas Dream Velvet",
"Christmas In Blue",
"Christmas Party",
"Christmas Rose Combo",
"Christmas Sock",
"Christmas Sparkle",
"Christmas Time",
"Chroma Thrill",
"Chrysanthemun",
"Chrysanthemun Cremon",
"Churchill",
"Ciara",
"Cielo",
"Cimarron",
"Cinderella",
"Cinerea",
"Cinnamon",
"Cioccolato",
"Circus",
"Cirque Dark",
"Citran",
"Clarice",
"Clarise",
"Clarissa",
"Class Act",
"Classic",
"Classic Cezanne",
"Classic Sensation Spray",
"Classic Woman",
"Classice Cezanne",
"Clear Water",
"Clearwater",
"Clemente",
"Cleo",
"Climax",
"Cloni",
"Cloni Felicidade",
"Cloni Fragolino",
"Cloni Peonia",
"Cloni Pon Pon",
"Cloni Success",
"Cloni Success Coral",
"Cloni Success Favola",
"Cloni Success Felicidade",
"Cloni Success Fragolino",
"Cloni Success Hanoi",
"Cloni Success Lady Pink",
"Cloni Success Lambada",
"Cloni Success Mambo",
"Cloni Success Mandarino",
"Cloni Success Nonno Antonio",
"Cloni Success Pink",
"Cloni Success Renoir",
"Cloni Success Touareg",
"Cloni Success Violet",
"Cloni Success White",
"Clooney",
"Clorophila",
"Clorophylia",
"Cloud",
"Cloudy Sky",
"Clove",
"Clover",
"Clown",
"Clue",
"Cobalt Thrill",
"Cobra",
"Cocarde",
"Coccolus",
"Cocculus",
"Cockscomb",
"Cocktail",
"Coco",
"Coco Avanti",
"Coco Bamboo",
"Coco Casino",
"Coco Kimono",
"Coco Mix",
"Coco Mix Trio",
"Coco Rio",
"Coco Tango",
"Coco Uno",
"Cocoa",
"Cocodrile",
"Coconut",
"Coctail",
"Codoo Roange",
"Coffee & Cream",
"Coffee Break",
"Coffee Latte",
"Colares",
"Cold",
"Cold Brew",
"Cold Play",
"Collin Lemon",
"Colombia",
"Come And Get Your Love",
"Command Performance",
"Companion",
"Concador",
"Concorde",
"Condenza",
"Cone",
"Conference",
"Confetti",
"Confetty",
"Confidential",
"Confite",
"Conga",
"Conquista",
"Constance",
"Constance-Austr",
"Constelation",
"Constellation",
"Cool Down",
"Cool Romance",
"Cool Water",
"Cooper",
"Copa Cabana",
"Copacabana",
"Copper Beech",
"Copper Extasis",
"Coqueta",
"Coral Charm",
"Coral Expression",
"Coral Fairy",
"Coral Passion",
"Coral Reef",
"Coral Sunset",
"Coral Xpression",
"Coral X-Pression",
"Coralie",
"Corallo",
"Corcega",
"Córcega!",
"Corcovado",
"Cordelia",
"Cordelini",
"Cordifilium",
"Cordyline Leaves",
"Cordyline Tips",
"Corelli Apricot",
"Corina",
"Corinto",
"Corleone",
"Corn Casserole",
"Cornbread",
"Corrida",
"Coruna",
"Coruña Bronze",
"Corvara",
"Corvara Pk",
"Corvette",
"Cosmic",
"Cossima",
"Costa",
"Costa Summer Lavender Iii",
"Costa Summer Orange Iii",
"Costa Summer Purple Iv",
"Costa Summer White Iii",
"Cote D Azur",
"Cote D'Azur",
"Cottage Yarrow",
"Cotton Candy",
"Cotton Candy Scoop",
"Cotton Gin",
"Cotton Xpression",
"Country",
"Country Aquarell",
"Country Blues",
"Country Candy",
"Country Garden",
"Country Home",
"Country Island Samoa",
"Country Louise",
"Country Secret",
"Country Spirit Louise",
"Country Sun",
"Courier",
"Cowboy",
"Cozumel Spray",
"Cozumen",
"Cranberry",
"Cranberry Sauce",
"Crane Feather Queen Red",
"Crane Red",
"Crane Rose",
"Craspedia Jumbo",
"Crassula",
"Crayola",
"Crazy",
"Crazy Diamond",
"Crazy Diamonds",
"Crazy Horse",
"Crazy On You",
"Cream Candy",
"Cream Expression",
"Cream Gracia",
"Cream Intermezzo",
"Cream Irischka",
"Cream Irishka-Sp",
"Cream Lydia",
"Cream Piaget",
"Cream Shimmer",
"Cream Viana",
"Cream Xpression",
"Cream Yves Piaget",
"Creamy Twister",
"Creme Brulee",
"Creme Brulle",
"Creme De La Creme",
"Creola",
"Cresta",
"Creta",
"Crimea",
"Crimson Spell",
"Crimson Tempo",
"Crispy Cream",
"Crissy",
"Cristal Clear",
"Crocosmia",
"Croton Leaves",
"Croton Tips",
"Crown",
"Crystal",
"Crystal Blanca",
"Crystal Blush",
"Crystal Clear",
"Crystal White",
"Cubana",
"Cuddle",
"Cuenca",
"Cumbia",
"Cumin",
"Cumosum Teretifolium",
"Cun 124",
"Cup",
"Cupid",
"Cupid #10 (Red/White/Pink)",
"Cupid Mix",
"Cupido",
"Curly Willow",
"Cushion",
"Cushion/Daisy",
"Cute Enigma",
"Cute G-150",
"Cynaroides",
"Cynaroides King Pink",
"Cypran",
"Cypress",
"Daisy",
"Dakar",
"Dalinda",
"Dallas",
"Dam Square",
"Damascus",
"Damina",
"Dancing",
"Dancing Queen",
"Dandy",
"Dang Sa Ard",
"Daniko",
"Dante",
"Darcey",
"Dark Bromo",
"Dark Captain Romance",
"Dark Emerald",
"Dark Engagement",
"Dark Expression",
"Dark Green",
"Dark Macchiato",
"Dark Mocca",
"Dark Orange Managua",
"Dark Pink",
"Dark Rendez Vous",
"Dark Rossano",
"Dark Xpression",
"Daucus",
"Dazzle",
"Db91717",
"Deborah",
"Deep Blue",
"Deep Faith",
"Deep Jay",
"Deep Lavender",
"Deep Pink Maxine",
"Deep Purple",
"Deep Silver",
"Deja Vu",
"Dejima",
"Dekora",
"Deli Rock",
"Delight",
"Delphi",
"Delphinium Sea Waltz",
"Dendrobium Angel Green",
"Dendrobium Beloved",
"Dendrobium Garland",
"Denim Collection",
"Denver",
"Depetaled",
"Desert",
"Desert Rose",
"Designer Dozen Rose Labor Saver",
"Designer Mix",
"Desna Bronze",
"Devotion",
"Dezna",
"Diamond",
"Diamond Rain",
"Diana Park",
"Dianthus Fresh",
"Dieffenbachia",
"Diego",
"Dijon",
"Diletta",
"Diletta Crema",
"Dimension",
"Dingo Fern",
"Dinner Plate",
"Dion",
"Dirty Dancing",
"Disco Club",
"Discovery",
"Diva",
"Divina",
"Dogwood",
"Dolores",
"Don Pedro",
"Donatello",
"Doncel",
"Donna",
"Doobadoo",
"Dordogne",
"Doria",
"Doris",
"Double",
"Double Cupid Gyp Combo",
"Double Dozen",
"Double Snowboard",
"Doublini",
"Doublini Brillianthus",
"Dozen",
"Dozen Color",
"Dozen Easter",
"Dozen Red Panther",
"Dozen Rose",
"Dr. Alexander Flemming",
"Draco",
"Dracula",
"Dragon Fly",
"Dream",
"Dream Catcher",
"Dream In Peach",
"Dreamland",
"Dromo",
"Drum",
"Drumstick",
"Dubai",
"Dubai Night",
"Dubium",
"Dubium Sunshine",
"Duchess De Nemours",
"Duchesse",
"Duchesse De Nemour",
"Duet",
"Duett",
"Dune",
"Dunya",
"Durban",
"Dusty Miller",
"Dusty Miller Broad Leaf",
"Dusty Miller Combo",
"Dusty Miller Lacey",
"Dusty Miller Lacy Leaf",
"Dusty Miller New Look",
"Dusty Miller Round",
"Dutch",
"Dutch Master",
"Dutch Single",
"Dutch Top Brass",
"Dylan",
"Dynamic",
"Dynamite",
"Dynamix",
"Eagle",
"Early Bird",
"Early Gray",
"Early Grey",
"Early Violet",
"Earrings",
"Earth",
"Earthworm",
"Easter",
"Easter Egg Hunt",
"Easter Festivity White",
"Easter Festivity Yellow",
"Easter Marshmellow Mix",
"Easter Rainbow Pastel",
"Easter Rose Bouquet",
"Easter Splash",
"Easter Sun",
"Easy Fashion",
"Echeveria",
"Echeverria",
"Echo",
"Eco",
"Ecu",
"Ecuadorian",
"Edge",
"Edith",
"Edsilia",
"Edulis Superba",
"Effie",
"Eggnog",
"Egyptian Fern/Fancy Podocarpus",
"Eilat",
"El Divo",
"Elatum",
"Elba",
"Elba!",
"Eldivo",
"Electra",
"Elegance",
"Elegance Bianco",
"Elegance Cioccolato",
"Elegance Clementine",
"Elegance Malva",
"Elegance Milka",
"Elegance Pastello Peach",
"Elegance Pastello Pink",
"Elegance Pastello Vintage",
"Elegance Rosa",
"Elegance Rosso",
"Elegant Rosever",
"Elena",
"Eleonora",
"Elf",
"Eliner",
"Elite",
"Elite Orange",
"Ella",
"Elsa Sass",
"Else Schluc",
"Elva",
"Emely",
"Emerald",
"Emerald Cb",
"Emerald Variegated",
"Emma",
"Emma Woodhouse",
"Empress",
"Emu Feather",
"Encanto",
"Enchante",
"Enchanted Rose Trio",
"Enchantment",
"Encourage",
"Endless Love",
"Endora",
"Energizer Bunny",
"Energy",
"Engagement",
"Engament",
"Enigma",
"Enjoy",
"Epilson",
"Epsilon",
"Equinox",
"Ercolano",
"Eremo",
"Erica",
"Erika",
"Eryngium Blue Lagoon",
"Escimo",
"Eskimo",
"Esmeralda",
"Espana",
"Esperance",
"Esponja",
"Esprit",
"Estelle",
"Estelle Spray Solidago",
"Estelle Tinted",
"Estrella",
"Etched Salmon",
"Ethylbloc Kit",
"Etna",
"Eucalyptus",
"Eucalyptus Baby Blue",
"Eucalyptus Cinerea",
"Eucalyptus Feather Willow",
"Eucalyptus Gunni",
"Eucalyptus Nicholli",
"Eucalyptus Parvifolia",
"Eucalyptus Polyantemus",
"Eucalyptus Pulverulenta",
"Eucalyptus Seeded",
"Eucalyptus Silver Diamond",
"Eucalyptus Silver Dollar",
"Eucalyptus Spiral",
"Eucalyptus Tinted",
"Eucalyptus Tinted And Glittered",
"Euforia",
"Eugenie",
"Euphorbia Snow On The Mountain",
"Euphoria",
"Euro Poms",
"Europa",
"Eva",
"Everest",
"Eversnow",
"Everton",
"Evidence",
"Ex Elegance",
"Excalibur",
"Excellence",
"Excellence Stars",
"Excellent Flair",
"Excellent Flair Spray",
"Exotic Sun",
"Exp.Chevere",
"Explo",
"Explorer",
"Express",
"Expresso",
"Extasis",
"Extreme Bicolor",
"Eye",
"Eyeliner",
"Eyerliner",
"Eze",
"Faboulus",
"Factor",
"Fado",
"Fair Banks",
"Fair Lady",
"Fairway",
"Fairy Dust",
"Fairytale",
"Faith",
"Fake Blood",
"Fake Snow",
"Falcao",
"Falkland",
"Falma",
"Fam",
"Famous",
"Fangio",
"Fantail",
"Fantasia",
"Fantasy Berry",
"Fantasy Glitter White Green",
"Fantasy Glitter White Pink",
"Fantasy Glitter White Turquoise",
"Fantasy Island",
"Fantasy Pistacho",
"Farfalla",
"Farfallina",
"Farida",
"Farieta",
"Fascination",
"Fashionista",
"Fastrada",
"Father Day",
"Fatima Spray",
"Fausto",
"Favourite",
"Faye",
"Feather King",
"Feather Queen",
"Febe",
"Feel",
"Feeling",
"Felicity",
"Felina",
"Felix Crouse",
"Felix Supreme",
"Fellini",
"Ferrari 4 Blooms",
"Festiva Maxima",
"Festival",
"Festivity",
"Fever Few",
"Feverfew Yellow",
"Fibonacci",
"Fibonacco Spiral",
"Fiction",
"Fidelity",
"Fidji",
"Fiebre",
"Fiesta",
"Fiesta Komachy",
"Fifi",
"Figaro",
"Finally",
"Finess",
"Fiorella",
"Fiorino",
"Fiorino Iris",
"Fiorino Leo",
"Fiorino Tatto",
"Fire King",
"Fire Up",
"Firebolt",
"Firenze",
"Firewalker",
"Firework",
"Fireworks",
"Firmenish",
"First Lady",
"Flag Bunch",
"Flambeau",
"Flame",
"Flame Giant",
"Flamenco",
"Flamenco Flame",
"Flaming Sunset",
"Flamingo",
"Flamingo Dutch",
"Flare Deep Blue",
"Flare Deep Rose",
"Flare White",
"Flare Yellow",
"Flash",
"Flash Baccara",
"Flash Eye",
"Flashpoint Double",
"Flemington",
"Fleur",
"Flexi Grass",
"Flirt",
"Florange",
"Floreana",
"Floreana!",
"Florence Nicholls",
"Floretta",
"Florex Gold",
"Floriano",
"Florida",
"Florida Grown",
"Florigene Moon Value Bunch",
"Florinca",
"Florinca Ballet",
"Florinca Captiva",
"Florinca Cherry",
"Florinca Dynamite",
"Florinca Fireflies",
"Florinca Marmara",
"Florinca Noah",
"Florinca Vogue",
"Florinca White Pearl",
"Flow Collection",
"Fluorite",
"Fly",
"Focal Baby Pink",
"Focal Scoop",
"Focal Scoop Blackberry",
"Focal Scoop Bonbon Vanilla",
"Focal Scoop Burgundy",
"Focal Scoop Dark Purple",
"Focal Scoop Hotpink",
"Focal Scoop Lavander",
"Focal Scoop Lilac",
"Focal Scoop Pk",
"Focal Scoop White",
"Focus",
"Fogata",
"Foggy Night",
"Foliage",
"Folies",
"Foratine",
"Foratini",
"Force",
"Forcer",
"Forest",
"Forever",
"Forever Young",
"Forrest Gump",
"Forsythia",
"Fortnite",
"Fortune",
"Fortuner",
"Forza Red",
"Four Queens",
"Foxy",
"Fragance",
"Fragrant Delicious",
"Francesca",
"Francine",
"Francis",
"Francois Rabelais",
"Fredy",
"Free",
"Free Spirit",
"Freedom",
"Freedom Ecu",
"Freedom Platinum Cut",
"Freedom Single Stem",
"French Camargue",
"French Maureen",
"French Oak",
"French Vanilla",
"Frescolita",
"Fresh",
"Freya",
"Frida",
"Friendly",
"Friends",
"Friendship",
"Frilled",
"Front Page",
"Frontera",
"Frost Wings",
"Frosted Amathyst",
"Frosted Tips",
"Frosty",
"Frotswings",
"Fruit Tart",
"Fruity Bubbles",
"Frutteto",
"Fruzzel",
"Fucsia",
"Fuego",
"Fuego Red",
"Fuente",
"Fuji",
"Full Monty",
"Full Of Charm",
"Full Star",
"Full Star White",
"Fully",
"Funny Girl",
"Fun-Sized",
"Furia",
"Fusion",
"Fuxia-Happy",
"Gabo",
"Gagarin",
"Gala Lavender",
"Gala Scarlet",
"Gala Yellow",
"Galactica",
"Galahad",
"Galaxi",
"Galaxia",
"Galaxy",
"Galicia",
"Gambur",
"Game On",
"Garden",
"Garden Gyp",
"Garden Mix",
"Garden Spirit",
"Gardenia",
"Garland",
"Garnet",
"Garnet Glow",
"Garnet Hybrid",
"Garota",
"Garuda",
"Gaviria",
"Geisha",
"Gem",
"Gem Star",
"Genzano",
"Georgia",
"Geraldine",
"Ghobi",
"Giallo Striato",
"Giant",
"Giant Blue",
"Giga Blanche",
"Giganteu",
"Ginger",
"Ginger Bread",
"Ginger!",
"Ginkgo",
"Ginza",
"Gioele",
"Gioia",
"Giole",
"Giotto",
"Giovanna",
"Giraffe",
"Girlfriend",
"Girlie Folies",
"Gisele",
"Giselle",
"Giselle Folies",
"Glacial Gypso",
"Glacier",
"Gladiator",
"Glady",
"Glamini",
"Glamini Ambar",
"Glamini Emmy",
"Glamini Jenny",
"Glamini Kelly",
"Glamini Kim",
"Glamini Lia",
"Glamini Pippy",
"Glamini Roxete",
"Glamini Silvia",
"Glamini Tom",
"Glestjer",
"Glimmer",
"Glittered",
"Glitz",
"Glitz Collection",
"Glitzi",
"Globe",
"Glory",
"Glory Rose Bouquet 6 Stem",
"Glow In The Dark",
"Go Green",
"Goanna Claw",
"Gobi",
"Goblin",
"Goddess",
"Gold",
"Gold & Brown",
"Gold Coin",
"Gold Crown",
"Gold Cup",
"Gold Dust",
"Gold Fever",
"Gold Finger",
"Gold Glitter Novelty",
"Gold Medal",
"Gold Star",
"Gold Strike",
"Gold Timana",
"Golda",
"Golden",
"Golden Blossoms",
"Golden Eye",
"Golden Gate",
"Golden Globe",
"Golden Glory",
"Golden Glory Ecuadorian",
"Golden Glory Yellow",
"Golden Medal",
"Golden Mustard",
"Golden Pass",
"Golden Polaris",
"Golden Pot Petals",
"Golden Pot Tips",
"Golden Praire",
"Golden Sensation",
"Golden Shamrock",
"Golden Stone",
"Golden Touch",
"Golden Tycoon",
"Golden Yellow",
"Goldfinch",
"Goldy Double",
"Golem",
"Golosina",
"Good Samaritan 8 Stem",
"Gospel",
"Gotcha",
"Govinda",
"Gracia",
"Gran Canaria",
"Gran Paradiso",
"Gran Sole",
"Granadier",
"Grand Amour",
"Grandiose",
"Grandola",
"Grandtastic",
"Granedier",
"Grape Velvet",
"Grassly",
"Grateful",
"Gratitude",
"Gravy",
"Gray Prolific",
"Gray Storm",
"Grazia",
"Greatful",
"Green",
"Green Ball",
"Green Ball 5 Stem",
"Green Ball Tinted And Glittered",
"Green Beauty",
"Green Bell",
"Green Center",
"Green Dragon",
"Green Eye",
"Green Fashion",
"Green Goddess",
"Green Jean",
"Green Jungle",
"Green Lagoon",
"Green M04",
"Green Mist",
"Green Planet",
"Green Prince",
"Green Ribbon",
"Green Romance",
"Green Tea",
"Green Wicky",
"Greenday",
"Gren Pink",
"Grenadier",
"Grenadine",
"Grevillea",
"Grey Knight",
"Grey Knights",
"Griffithi",
"Griffiti",
"Groom",
"Grow Positive Rose Bunch",
"Guadalupe",
"Guajira",
"Guapa",
"Gucci",
"Guican",
"Guinevere",
"Guinness",
"Gunnii",
"Gustav",
"Gyp Asst",
"Gyp Cloud",
"Gypsi Curiosa",
"Gysela Folies",
"H Pink",
"Habana",
"Hallelujah",
"Halloween",
"Halloween Collection",
"Halloween Festivity",
"Halloween Festivity Ii",
"Halloween Rainbow Roses",
"Halo",
"Hamada",
"Handsome",
"Handsome Pink",
"Hanging",
"Hanging Mira",
"Hanna",
"Hanoi",
"Hanoi Focal Scoop",
"Happiness",
"Happy",
"Happy Bride",
"Happy Golem",
"Happy Moon",
"Hard Rock",
"Harlem",
"Harley",
"Harvey",
"Havana",
"Hawaii",
"Hawaii Gold",
"Hawaiian Dream",
"Hawaiian Papaya",
"Hazelnut Harmony",
"Heart",
"Heart Majestic",
"Heart Of Gold",
"Heart Of Mustard",
"Heartbeat",
"Hearts",
"Hearts Of Gold",
"Hearts Stamp",
"Hearts/Wanted",
"Hebes",
"Heidy",
"Heirloom",
"Heliconia Upright",
"Helios",
"Helios Flame",
"Hellen",
"Helmar",
"Helvetia",
"Henry Bockstoce",
"Her Majestic",
"Hercules",
"Heritage",
"Hermes",
"Hermes Orange",
"Hermione",
"Hermosa",
"Hettie",
"High & Arena",
"High & Bonita",
"High & Booming",
"High & Candy",
"High & Exotic",
"High & Happy",
"High & Intenzz",
"High & Magic",
"High & Orange",
"High & Peace",
"High & Peach",
"High & Sol",
"High & Sunshine",
"High & Yellow",
"High & Yellow Flame",
"High & Yellow Magc",
"High & Yellow Magic",
"High And Yellow Magic",
"High Gold",
"High Intenze",
"High Magic",
"High Orange Magic",
"Highlight",
"Hilux",
"Himalaya",
"Hinault",
"Hippie",
"Hiroko",
"Hiyoli",
"Ho Ho Ho",
"Holanda",
"Holland Art",
"Holmes",
"Homerus",
"Honesty",
"Honey",
"Honey Apricot",
"Honey Bell",
"Honey Bracelet",
"Honey Flair",
"Honey Mocca",
"Honey Moon",
"Honeymoon",
"Hong Kong",
"Honor",
"Honor Attendant",
"Hope",
"Hornbill",
"Hot Biscuit Upright",
"Hot Carpediem",
"Hot Cherry",
"Hot Chocolate",
"Hot Desire",
"Hot Explorer",
"Hot Lady",
"Hot Lady Yambo",
"Hot Lava",
"Hot Majolica",
"Hot Majolika",
"Hot Merengue",
"Hot Mia",
"Hot Paris",
"Hot Party",
"Hot Pepper",
"Hot Pink",
"Hot Pink Folies",
"Hot Pink Tinted Black Outer Petals",
"Hot Princess",
"Hot Rod",
"Hot Sauce",
"Hot Shot",
"Hot Spot",
"Hot Xpression",
"Hotrod",
"Hotspot",
"Houdini Summerhouse",
"Huckleberry",
"Hulk",
"Hummer",
"Hurricane",
"Hyacinth",
"Hybrid",
"Hybrid Ariel",
"Hybrid Ariel Triton",
"Hybrid Black Night",
"Hybrid Blue",
"Hybrid Candle",
"Hybrid Candle Violet",
"Hybrid Champagne Pedara",
"Hybrid Elatum",
"Hybrid Elatum Asia",
"Hybrid Elatum Black Velvet",
"Hybrid Elatum Blue River",
"Hybrid Elatum Full Moon",
"Hybrid Elatum Lavender",
"Hybrid Elatum Manuela",
"Hybrid Elatum River",
"Hybrid Elatum Sky",
"Hybrid Elatum White River",
"Hybrid Forza",
"Hybrid Pacific",
"Hybrid Pacific Astolat",
"Hybrid Pacific Benary",
"Hybrid Pacific Blue Bird",
"Hybrid Pacific Blue Jay",
"Hybrid Pacific Blush Rose",
"Hybrid Pacific Galahad",
"Hybrid Pacific Summer Skies",
"Hybrid Triton",
"Hydra",
"Hydrangea",
"Hydrangea Red Green",
"Hypnosis",
"I Want You Back",
"Ibis",
"Ibis Escarlata Dutch",
"Ibiza",
"Ice",
"Ice Cap",
"Ice Cream",
"Ice Crystal",
"Ice Follies",
"Ideal",
"Idilia",
"Idole",
"Igloo",
"Iguana",
"Iguazu",
"Ikebana",
"Ilex",
"Ilex Verticillt",
"Ilsa",
"Ilse",
"Ilusion",
"Ilusion Polar",
"Ilussion",
"Imagination",
"Imagine",
"Immaculee",
"Immortal Rose Bouquet",
"Imogen",
"Impact",
"Impression",
"Inca",
"Indian Diamond",
"Indian Summer",
"Indian Summerset",
"Indiana",
"Indira",
"Inferno",
"Infinite Love",
"Inocencia",
"Inspeacteur Lavergne",
"Inspiration",
"Intenz Pink",
"Intenze",
"Inter Dark Pink",
"Intermezzo",
"Inti",
"Ireland",
"Iris",
"Irischka",
"Irish Pub Combo",
"Irishka",
"Irishka-Sp",
"Isabel",
"Isabella",
"Isis",
"Isola",
"Israeli",
"Istanbul",
"Italian Ivy",
"Italian Mini Variegated Pittosporum",
"Italian Oak Autumn",
"Italian Variegated Pittosporum",
"Ivana Dark Orange",
"Ivana Orange",
"Ivory",
"Ivory Art",
"Ivy",
"Jacaranda",
"Jacintha",
"Jackpot",
"Jacorma",
"Jade",
"Jade Gold",
"Jaffa",
"Jalah",
"Jamaica",
"Jamey Dark",
"Jana",
"Janeiro",
"Janelle",
"Japanese Minami",
"Japanese Minami Feminine",
"Japanese Minami Lemon",
"Japanese Minami Novelty",
"Japanese Minami Orange",
"Japanese Minami Passion",
"Japanese Minami Poly",
"Japanese Minami Sakura",
"Japanese Minami Tommy",
"Japanese Rainbow",
"Jasmin",
"Jasmina",
"Jasmine Vine",
"Jay",
"Jeanine",
"Jeanne Moreau",
"Jeannine",
"Jelena",
"Jelly",
"Jelly Bean",
"Jessika",
"Jester",
"Jet Set",
"Jewel",
"Jeweler",
"Jobim",
"Jockey",
"Jodie",
"Jolie",
"Joop",
"Josephine",
"Joshua",
"Journey",
"Joy",
"Joyce",
"Juana",
"Juanita",
"Jubilee",
"Juicy Fresh",
"Jules Eli",
"Jules Elie",
"Julia",
"Juliet",
"Juliete",
"Juliette",
"July",
"Jumbo",
"Jungle Roman",
"Jungle Romance",
"Jupiter",
"Just Can'T Get Enough",
"Just Magic",
"Just Peachy Spray",
"Just The Two Of Us",
"Jyoti",
"K Dozen Roses Color",
"K Dozen Roses Red",
"K2",
"Kabuki",
"Kadango",
"Kadanz",
"Kahala",
"Kale",
"Kale Antonia",
"Kale Crane",
"Kale Crane Lace",
"Kale Flowering",
"Kale Lacy",
"Kale Rosse",
"Kale Ruffle",
"Kale Varvara",
"Kalua",
"Kamaliya",
"Kamila",
"Kamishi",
"Kampala",
"Kangaroo Paw",
"Kangaroo Paw Cb",
"Kansas",
"Kaori",
"Karen",
"Karibu",
"Karina",
"Karl Rosenfield",
"Karma",
"Karma Amora",
"Karma Choc",
"Karma Corona",
"Karma Corona Pink",
"Karma Fox Maroon",
"Karma Fox Orange",
"Karma Moon Lady",
"Karma Prospero",
"Kastelli",
"Kate",
"Katherina",
"Kavery",
"Keano",
"Kehla",
"Keira",
"Kelah",
"Kelly",
"Kennedy",
"Kerio",
"Khela",
"Kiara",
"Kibo",
"Kimberly",
"King Bubbles",
"King Cross",
"King Kong",
"King White",
"Kino",
"Kintaro",
"Kipling",
"Kirvy",
"Kiss",
"Kiss Me",
"Kiwi",
"Kiwi Boom",
"Kiwi Cherry",
"Kiwi Mellow",
"Koala Fern",
"Kodiak",
"Komachi",
"Konfetti",
"Krakatoa",
"Kristel",
"Kumquat",
"Kunming",
"Kurosowa",
"La Paz",
"La Perla",
"La Perle",
"La Vie En Rose",
"Lace",
"Lacy Leaf",
"Lady Bombastic",
"Lady Daiki",
"Lady Di",
"Lady In Green",
"Lady In Red",
"Lady Katherine",
"Lady Luck",
"Lady Mali",
"Lady Marmalade",
"Lady Marmelade",
"Lagoon",
"Laguna",
"Lake Carey",
"Lambretta",
"Lambrusco",
"Lamira",
"Lantern Rose Bunch",
"Lanuginosa",
"Laser",
"Latin Beauty",
"Latin Circus",
"Latin Lady",
"Latina",
"Latte",
"Lavander Irischka",
"Lavanrose",
"Lavender",
"Lavender Bouquet",
"Lavender Dry",
"Lavender Irishka",
"Lavender Irishka-Sp",
"Lavender Latte",
"Lavender Scoop",
"Le Baron",
"Lea Romantica",
"Leah",
"Leather Leaf",
"Leather Leaf Jr",
"Leather Leaf Md",
"Leather Leaf Short",
"Leather Leaf Sleeved",
"Lega",
"Lege",
"Lege Marrone",
"Lege Pink",
"Legend",
"Legue Marrone",
"Leila",
"Lemon Cream Cake",
"Lemon Passion",
"Lemon Pie",
"Lemon Pompon",
"Lemon Sky",
"Lemon Twist",
"Lemonade",
"Lemoncello",
"Lenne",
"Lennox",
"Leones",
"Leonidas",
"Leonora",
"Leprechaun",
"Lesbos",
"Lesotho",
"Leucadendron Discolor",
"Leucadendron Don Jose",
"Leucadendron Jester",
"Leucadendron Pom Pom",
"Level Up",
"Levis Wings",
"Lexington",
"Lexy",
"Lexy Red",
"Leyland Cypress",
"Light Emerald",
"Light Explorer",
"Light Orlando",
"Light Pink",
"Light Romance",
"Light Spirit",
"Light Star",
"Lighthouse",
"Ligustrum",
"Like A Virgin",
"Lila",
"Lilac",
"Lilac Dreams",
"Lilac Focal Scoop",
"Lilipot White",
"Liliput Forever",
"Lilliput Forever",
"Lilliput Papillon",
"Lilliput Snow",
"Lily Grass",
"Lily Grass Green",
"Lily Grass Variegated",
"Lily Of The Valley",
"Limbo",
"Lime Green",
"Limonada",
"Lina",
"Lindsey",
"Linette",
"Linnette",
"Linx",
"Lion King",
"Lionheart",
"Liquidambar",
"Litouwen",
"Little Silver",
"Liz",
"Lizzy",
"Lodi",
"Logan",
"Loire",
"Loki",
"Lola",
"Lola Bunny",
"Loli",
"Lolita",
"Lollipop",
"Lombardia",
"Longwood",
"Lore",
"Lorena",
"Lorena Summerhouse",
"Lorenzo",
"Lorraine",
"Lotus",
"Lotus Dark",
"Louis",
"Louis Van Hout",
"Louise",
"Louisiana",
"Love Bites",
"Lovely",
"Lovely Hearts",
"Lovely Lavender",
"Lovely Lidia",
"Lovely Lydia",
"Lovely Romance",
"Loves Me",
"Lowland",
"Lucero",
"Lucia",
"Luciano",
"Lucidum",
"Luck",
"Lucky Green Romance",
"Lucky Lilac",
"Lucky Romance",
"Lucy",
"Luiza",
"Lumia",
"Luviana",
"Luxor",
"Lycia",
"Lydia",
"Lynn",
"Lynx",
"Mac & Cheese",
"Macarena",
"Macchiato",
"Madalay",
"Madame Bombastic Spray",
"Madame Claude Tain",
"Maddox",
"Madeira",
"Madelon",
"Madera",
"Madiba",
"Madonna",
"Madonna Dutch",
"Magenta Bicolor",
"Maggi",
"Maggie",
"Magic",
"Magic Combo Box",
"Magic Lips",
"Magic Mocca",
"Magic Rose",
"Magic Times",
"Magical",
"Magical Bloody Mary",
"Magical Blue",
"Magical Blue Lagoon",
"Magical Cherry",
"Magical Green",
"Magical Ivory",
"Magical Light Pink",
"Magical Love",
"Magical Majestic",
"Magical Majestic Pink",
"Magical Midnight",
"Magical Passion",
"Magical Pink",
"Magical Polar",
"Magical Pumpkin",
"Magical Purple",
"Magical Queen",
"Magical Red",
"Magical Red Wine",
"Magical Renata",
"Magical Royal Princess",
"Magical Series",
"Magical Silver",
"Magical Silver Lagoon",
"Magical Snow Prince",
"Magical Summersun",
"Magical Terracota",
"Magical Triumph",
"Magical Universe",
"Magical Victory",
"Magical Victory Ii",
"Magical Victory Spray",
"Magical White Lagoon",
"Magna",
"Magnifica",
"Magnificent Bells",
"Magnum",
"Magnum Blue",
"Magnum Yellow",
"Maiden Hair Fern",
"Maike",
"Maine Blue",
"Maine Blue Ecuador",
"Maine Blue Peru",
"Maira/Romi",
"Maisy",
"Maisy Spray",
"Majestic",
"Majestic Red",
"Majolica",
"Maki",
"Makuahine",
"Makuii",
"Makwi",
"Malbec",
"Maldano",
"Malena",
"Malibu",
"Malu",
"Malva",
"Mama",
"Mama 12 Stem",
"Mama Mia",
"Mambo",
"Mami Blue",
"Mamma Mia",
"Mamma Mia !!",
"Mammy Blue",
"Managua",
"Manaure",
"Mandala",
"Mandalay",
"Mandalay Bay",
"Mandarin Xpression",
"Mandarina",
"Mandaro",
"Mango",
"Manifesto",
"Manila",
"Manitou",
"Mansfield Park",
"Mantua",
"Maple Syrup",
"Mar",
"Maracana",
"Marble",
"Mardi Gras",
"Mari",
"Mariachi",
"Mariah",
"Mariam",
"Marian",
"Mariatheresia",
"Marie Lemoine",
"Marigold Coco",
"Marigold Coco Deep",
"Marinda",
"Marinilla",
"Mariposa",
"Marisa",
"Maritime",
"Marjan",
"Marjorie",
"Mark Twain",
"Marleny",
"Marlon",
"Marlyse",
"Marrone",
"Marsala",
"Marshmallow",
"Marshmallow Scoop",
"Martina",
"Martina Pink",
"Martini",
"Marty",
"Marvel",
"Marvellous",
"Marvellous Bubbles",
"Mary E Nicholls",
"Marylin",
"Marzipan",
"Mask",
"Massive",
"Master",
"Mata-Hari",
"Matcha",
"Matchpoint",
"Matilda",
"Matka",
"Matricaria",
"Matsumoto",
"Matsumoto Peruvian",
"Mayfair",
"Mayra",
"Mayra Bright",
"Mayra Flamingo",
"Mayra's",
"Mayra's Brick",
"Mayra's Bridal",
"Mayra's Citric",
"Mayra's Collection",
"Mayra's Fantasy",
"Mayra's Fucsia",
"Mayra's Green",
"Mayra's Hot Pink",
"Mayra's Peach",
"Mayra's Pink",
"Mayra's Red",
"Mayra's Rose",
"Mayra's Rose Bridal Pink",
"Mayra's Rose Collection",
"Mayra's Rose Green / Cream",
"Mayra's Rose Peach",
"Mayra's Rose Pink",
"Mayra's Rose Red",
"Mayra's Rose Rojo",
"Mayra's Rose White",
"Mayra's Vert",
"Mayra's Vintage",
"Mayra's White",
"Mayra's Yellow",
"Mccallum Bogota",
"Mccallum Ecuador",
"Mccallum Medellin",
"Mday Colors",
"Medium",
"Medium Pink",
"Megan",
"Melba",
"Melissa",
"Mellow",
"Mellow Orange",
"Mellow Romance",
"Melodia",
"Melody",
"Melrose",
"Member Rojo",
"Memorial Collection",
"Memphis",
"Menorca",
"Menta",
"Meraki",
"Mercedes",
"Mercury",
"Mere",
"Merengue",
"Meribel",
"Merida",
"Meridianum",
"Meriva",
"Merketto",
"Merlet",
"Merletto",
"Merletto Bishop",
"Merletto Cherry",
"Merletto Crimson",
"Merletto Green",
"Merletto Purple",
"Merlot",
"Merlot Focal Scoop",
"Merlot Power",
"Merluza",
"Mermaid",
"Mermaid Kisses",
"Merostar",
"Metalica",
"Metallic",
"Metropolitan",
"Mexican Myrtle",
"Mia",
"Michael",
"Michelle",
"Midnight",
"Mignon",
"Mikado",
"Mikaela",
"Miku",
"Mila",
"Milima",
"Milka",
"Milkana",
"Milkay Way",
"Milky Scoop",
"Milky Way",
"Milky White",
"Milla Aubergine",
"Milla Deep Rose",
"Milla Lavender",
"Milla Purple",
"Millenial",
"Millicent",
"Million Star",
"Million Star 2.0",
"Million Star Glitter",
"Million Star Tinted",
"Million Star Tinted W/ Silver Glitter",
"Milly",
"Milonga",
"Milos",
"Milou",
"Milva",
"Mimosa",
"Minerva",
"Mingus",
"Mini",
"Mini Green Airbrushed",
"Miniom",
"Minion",
"Minnou",
"Mint",
"Minueto",
"Minuetto",
"Mirabel",
"Mirabella",
"Miracle",
"Mirage",
"Miranda",
"Misaki",
"Miss Blanca",
"Miss Bombastic Spray",
"Miss Marple",
"Miss Piggy",
"Miss White",
"Mist",
"Mistery",
"Mistique",
"Mistletoe",
"Mistral",
"Mistral Blue",
"Mistral Plus",
"Mistral White",
"Misty",
"Misty Blue",
"Misty Tinted",
"Misty White",
"Misuki",
"Mitra",
"Mix",
"Mixtos Amarillos",
"Miyabi",
"Miyabi Brown",
"Mizuki",
"Mocca",
"Mocca Latte",
"Mocca Medium",
"Mocca Sand",
"Mocha Sweet",
"Mochi",
"Modena",
"Mohana",
"Mojave",
"Mojito",
"Mokara Blue Nora Blue",
"Mokara Pink Chub Kuan",
"Mokara Purple Anne Cool",
"Molly",
"Molto Dark",
"Mom",
"Momentum",
"Momentum+",
"Mommy Dearest",
"Mompox",
"Mon Cheri",
"Monaco Red",
"Monarca",
"Monarch",
"Monarch Purple",
"Mondial",
"Monica",
"Monsenor",
"Monseñor",
"Monsieur Jules Elie",
"Monster",
"Monstera Leaf",
"Monstera Leaves",
"Mont Blanc",
"Montana",
"Montblanc",
"Monte Azzurro",
"Monte Bianco",
"Monte Carlo",
"Monte Vecchio",
"Montebello",
"Montelava",
"Monteneu",
"Montenew",
"Montes",
"Monteverde",
"Montezuma",
"Month Blanc",
"Montoya",
"Moody Blues",
"Moon Golem",
"Moon Light",
"Moon Over Barrington",
"Moon Series",
"Moon Stone Hybrid",
"Moonaqua",
"Moonberry",
"Moonblossom",
"Moonburst",
"Mooncherry",
"Moondance",
"Moonique",
"Moonivory",
"Moonlight",
"Moonlite",
"Moonpearl",
"Moonserie Asst",
"Moonseries",
"Moonshade",
"Moonshadow",
"Moonsnow",
"Moonstone",
"Moonstrike",
"Moontea",
"Moonvelvet",
"Moonvista",
"Mor",
"Morena",
"Morgan",
"Morisca",
"Morning Sun",
"Mosaic",
"Mosaico",
"Moscow",
"Mostera Leaf",
"Mother Choice",
"Mother Of Choice",
"Mother Of Pearl",
"Mother’S Day Dozen 19 Stem",
"Mothers Choice",
"Mothers Day Mix",
"Motown",
"Mount Everest",
"Mount Hunter",
"Mountain Rose",
"Movie Star",
"Mozart",
"Muscari",
"Music",
"Mustard",
"Mutter",
"Mygreen",
"Mynnou",
"Myrthe",
"Myrtle",
"Mystique",
"Mythos",
"Nadia",
"Nadya",
"Nagi",
"Nahema",
"Nairobi",
"Namaste",
"Namib",
"Nandi",
"Nandy",
"Naomi",
"Napoli",
"Nashville",
"Natalia",
"Natalya",
"Natascha",
"Natasha",
"Nathalie",
"Natural",
"Natural Rachel",
"Natures Cherry",
"Nature'S Cherry",
"Nature'S Peach",
"Nautica",
"Nautilus",
"Navarro",
"Navona",
"Navy Sun Birds",
"Necklace",
"Nectarine",
"Needle",
"Negrita",
"Nemo",
"Nena",
"Nenufar",
"Neo",
"Neon",
"Neon Purple",
"Nepal",
"Nerello",
"Nerine",
"Nestor",
"Nevada",
"New Aqua",
"New Face",
"New Love",
"New Mix",
"New Red",
"New Vogue",
"New Yellow",
"New York",
"Newlove",
"News Flash",
"Newton",
"Nexus",
"Nexxus",
"Nicoletta",
"Nieve",
"Nigella",
"Night Cap",
"Night Fall",
"Night Thrill",
"Nightlife",
"Nimbus",
"Nina",
"Nina Helix Hybrid",
"Nirvana",
"Noa",
"Nobbio",
"Nobbio Argenta",
"Nobbio Black Heart",
"Nobbio Burgundy",
"Nobbio Cabaret",
"Nobbio Cassi",
"Nobbio Cherry",
"Nobbio Circus",
"Nobbio Collection",
"Nobbio Dolce Nero",
"Nobbio Filigrana",
"Nobbio Gelato",
"Nobbio Heart",
"Nobbio Party",
"Nobbio Pink",
"Nobbio Violet",
"Nobia",
"Noble Fir",
"Noblesse",
"Nofa",
"Noir",
"Nora",
"Norma",
"North Wind",
"Notre Dame",
"Nova Scotia",
"Nova Zembla",
"Novastar",
"Novelty",
"Amaris",
"Amor Dreamy",
"Amor Tangerine",
"Ast",
"Bolte",
"Bronze Bombay",
"Cronox",
"Curazao",
"Einstein",
"Empatia Sunset",
"Fuji Yellow",
"Grace",
"Ivannovo",
"Jombe",
"Joya",
"Kogui",
"Manzana",
"Orange Bradford",
"Orange Florange",
"Picara",
"Pixel Tesoro",
"Radost",
"Red Bradford",
"Red Hot Rod",
"Rioja",
"Roma Festa",
"Secret",
"Shortcake",
"Smashing",
"Solar Eclipse",
"Starburst",
"Sundi",
"Thypoon",
"Tiara",
"Tinsel",
"Topspin",
"Toulouse",
"Troyes",
"Turo",
"Vibowl",
"Yellow Sunny Ilias",
"Zamora",
"Zippo",
"Novi",
"Novia",
"Number One",
"Nymph",
"Oak",
"Oak Forest",
"Oasis",
"Oba Oba",
"Ocean Mikado",
"Ocean Mist",
"Ocean Song",
"Odeon",
"Odesa",
"Odessa",
"Odile",
"Odilia",
"Ofir",
"O'Hara",
"Ohio",
"Okaasan",
"Oki Doki",
"Okinawa",
"Old Faithful",
"Ole",
"Olga",
"Olimpia",
"Olive",
"Olivino",
"Olympia",
"Onyx",
"Oops",
"Opal",
"Opala",
"Open Cut",
"Opera",
"Opus",
"Opus Iii Lavender",
"Opus Iii Red",
"Opus Iii Yellow",
"Opus Iii/Iv White",
"Opus Iv Fresh White",
"Orae",
"Oranda",
"Orange",
"Orange Babe",
"Orange Bowl",
"Orange Crush",
"Orange Emperor",
"Orange Enigma",
"Orange Flame",
"Orange Hybrid",
"Orange Mambo",
"Orange Managua",
"Orange Only",
"Orange Quartz",
"Orange Queen",
"Orange Reeva",
"Orange Sensation",
"Orange Star",
"Orange Stone",
"Orange Success",
"Orange Tresor",
"Orange Triumph",
"Orange Tycoon",
"Orange Unique",
"Orange Viana",
"Orchids",
"Oregon",
"Oregonia",
"Original Love",
"Orinoco",
"Orlando",
"Orleans Yellow Iv",
"Ornella",
"Oshi",
"Oshi Pink",
"Osiana",
"Ovation",
"Overtime",
"Overture Ii Orange",
"Oxygen",
"Pacal",
"Paciano",
"Pacific",
"Pacific Amber",
"Pacific Astolat",
"Pacific Blue Bird",
"Pacific Blue Jay",
"Pacific Burgundy",
"Pacific Galahad",
"Pacific Giant White",
"Pacific King Arthur",
"Pacific Red",
"Pacific Summer Skies",
"Paco",
"Padraig Sona",
"Paintball",
"Paintball Jumbo",
"Paintball Jumbo Fall",
"Paintball Jumbo V-Day",
"Paintball Sunny",
"Paintball Yellow",
"Paintball Yellow Jumbo",
"Painted",
"Painted Christmas",
"Painted Football",
"Painted On Red Base",
"Paishman",
"Paladov",
"Paladov Sunny",
"Palena",
"Palermo",
"Palm",
"Palmetto Fan",
"Palmira",
"Paloma",
"Pampas",
"Pampas Arrow",
"Pampas Fluffy",
"Panama",
"Panda",
"Pandanus",
"Pandanus Medium",
"Pandanus Twisted",
"Pandora",
"Panned Chocolate Egg",
"Panorama Egg",
"Panoramic Egg",
"Panther",
"Paola",
"Paoletto",
"Papaya",
"Parade",
"Paradero",
"Paraguay",
"Paranoya",
"Pardraig Sona",
"Paris",
"Parker Yarrow",
"Parmida",
"Parrot",
"Paru",
"Parvifolia",
"Pascoli",
"Pascua",
"Pashmina",
"Pasion Almendra",
"Pasion Toscano",
"Paso Doble",
"Passion",
"Passion Combo",
"Passion De Almendra",
"Passion Fruit",
"Passion Heat",
"Passion Sunset",
"Pastel",
"Pastella",
"Pastello",
"Patersonii",
"Patience",
"Patiende",
"Patricia",
"Patriot",
"Patriotic",
"Patriotic Crazy Daisy",
"Paul M. Wild",
"Paula Fay",
"Paulina",
"Pavarotti",
"Pavia",
"Paz",
"Peace",
"Peach",
"Peach Aubade",
"Peach Avalanche",
"Peach Expression",
"Peach Irishka",
"Peach Mambo",
"Peach Melba",
"Peach Spirit",
"Peach Temptation",
"Peach Wave",
"Peach Xpression",
"Peach X-Pression",
"Peachy Mambo",
"Pearl Finess",
"Pearl Finesse",
"Pearl Pink",
"Pearls Petite",
"Pecher",
"Peckoubo",
"Peeps",
"Pegaso",
"Pencil",
"Penelope",
"Pennycress",
"Pennycress Minicoins",
"Peppermint",
"Peppermint Rose Bouquet 10 Stem",
"Peps",
"Peptalk",
"Perfection",
"Peridot",
"Perigord",
"Periwinkle Blush",
"Perla",
"Perla Negra",
"Perle Rose",
"Persia",
"Peru",
"Peruvian",
"Petacas",
"Petal Bags",
"Peter Brandt",
"Peters Pride",
"Petite 5 Stem",
"Petite Aimee",
"Petite Fleur",
"Petite Odile",
"Petite Uzu",
"Petronella",
"Petrushka",
"Petruska",
"Phalaenopsis",
"Pho Tie Dyed Roses",
"Phoebe",
"Phoenix",
"Phoenix Roebelenii",
"Photinia",
"Phuket!",
"Piacere",
"Piano",
"Picanto",
"Picasso",
"Pic-Nic",
"Pico",
"Picote",
"Picote Blue",
"Picote Pink",
"Piet",
"Pigato",
"Pigeon",
"Pigota",
"Pillow Talk",
"Pimpinela Spray",
"Pin Cushion",
"Pin Cushion Red",
"Pina Colada",
"Piña Colada",
"Pincushion",
"Pincushion Ayoba",
"Pincushion Emily",
"Pincushion Empress",
"Pincushion Flame",
"Pincushion Goldie",
"Pincushion High Gold",
"Pincushion Megan",
"Pincushion Moonlight",
"Pincushion Neena",
"Pincushion Rigoletto",
"Pincushion Soleil",
"Pincushion Succession",
"Pincushion Sunfire",
"Pincushion Sunflame",
"Pincushion Super Gold",
"Pincushion Tango",
"Pincushion Tiara",
"Pine Cypress",
"Pine Tips",
"Pineapple Ananas Purple Mini",
"Pineapple Large Pink",
"Pineapple Mini Pink",
"Pineapples",
"Pink",
"Pink Amaretto",
"Pink Beauty",
"Pink Brenda",
"Pink Bubbles",
"Pink Candy",
"Pink Curie",
"Pink Diamond",
"Pink Doll - Diamond Castle",
"Pink Doll - Dreamtopia",
"Pink Doll - Fairy Secret",
"Pink Doll - Princess Charm",
"Pink Doll Collection",
"Pink Dream",
"Pink Dreamland",
"Pink Elegance",
"Pink Escimo",
"Pink Explorer",
"Pink Expresion",
"Pink Expression",
"Pink Farfalla",
"Pink Flamingo",
"Pink Flash",
"Pink Floyd",
"Pink Giant",
"Pink Gracia",
"Pink Heart",
"Pink Ice",
"Pink Intuition",
"Pink Irischka",
"Pink Irishka",
"Pink Irishka-Sp",
"Pink Jewell",
"Pink King",
"Pink Love",
"Pink Majolica",
"Pink Majolika",
"Pink Mondial",
"Pink Monster",
"Pink Neon",
"Pink O'Hara",
"Pink Passion",
"Pink Piano",
"Pink Pigeon",
"Pink Porcelain",
"Pink Posh",
"Pink Prom",
"Pink Puma",
"Pink Puppy",
"Pink Quartz Hybrid",
"Pink Royalist",
"Pink Sand",
"Pink Sensation",
"Pink Sherbet Scoop",
"Pink Spirit",
"Pink Virginia",
"Pink Xpression",
"Pink X-Pression",
"Pinkie",
"Pinkrock",
"Pinkrock Dark",
"Pinky Promise",
"Pinky Rock",
"Pinotage",
"Pippa Wings",
"Pirandello",
"Piranga",
"Pisco",
"Piston Cup",
"Pita",
"Pitto Nigra",
"Pittosporum",
"Pittosporum Green",
"Pittosporum Variegated",
"Piuma",
"Piuma Dark Blue",
"Pixel",
"Planeta Rojo",
"Planum",
"Plasma",
"Platina",
"Playa Blanca",
"Playtime",
"Plumosum",
"Plumosum Spray",
"Plumosus",
"Pod",
"Podocarpus Maki",
"Pods",
"Poison Ivy",
"Pokers",
"Polar",
"Polar Gypso",
"Polar Route",
"Polar Sensation",
"Polar Star",
"Polaris",
"Polimnia",
"Polo",
"Pom Masive",
"Pom Melrose",
"Pomarosa",
"Pomegranate Punch",
"Pomodoro",
"Pompeii",
"Pompini",
"Pon Pon",
"Pon Pon Aurora",
"Pon Pon Draco",
"Pon Pon Dragon Fruit",
"Pon Pon Fanny",
"Pon Pon Flora",
"Pon Pon Garfield",
"Pon Pon Igloo",
"Pon Pon Magenta",
"Pon Pon Magic",
"Pon Pon Merlino",
"Pon Pon Minerva",
"Pon Pon Pink Lemonade",
"Pon Pon Silente",
"Pon Pon Stella",
"Pon Pon Trilly",
"Pop",
"Pop Yellow",
"Popcorn",
"Porcelain",
"Porcelana",
"Porcelina",
"Port Orford Cedar",
"Portrait",
"Pot Of Gold",
"Potato Rolls",
"Pothinia",
"Potion Pot",
"Potomac",
"Potomac Crimson",
"Potomac Dark Orange",
"Potomac Early Pink",
"Potomac Early White",
"Potomac Early Yellow",
"Powder Puff China Aster",
"Power",
"Prado",
"Prado Mint",
"Pre Intenzz",
"Precioso",
"Precious Metal",
"Precious Moments",
"Premium",
"Premium Blond",
"Premium Blonde",
"Premiun Cut",
"President Franklin",
"President Lincoln",
"Pretty Art",
"Pretty In Pink",
"Pretty Tessino",
"Priceless",
"Pride",
"Pride 12 Stem",
"Primadona",
"Primadonna",
"Primavera",
"Primavera Rose",
"Prime",
"Prime Alma Fresca Gold",
"Prime Cantor Fresca Gold",
"Prime Captain Promise",
"Prime Denver Fresca Gold",
"Prime Fresca Gold",
"Prime Gold Medal",
"Prime Mango Fresca Gold",
"Prime Perla",
"Prime Pink Dreamland",
"Prime Promise Fresca Gold",
"Prime Red Emotion",
"Prime Romance Fresca Gold",
"Prime Samba",
"Prime Sumatra",
"Prime Sumatra Fresca Gold",
"Prime Time",
"Prime Trinity",
"Prime Ventura Fresca Gold",
"Prince Jardinier",
"Prince Jardiniere",
"Princess",
"Princess Aiko",
"Princess Charlene",
"Princess Collection",
"Princess Crown",
"Princess D.P.",
"Princess Fairy Kiss Spray",
"Princess Hitomi",
"Princess Hoshi",
"Princess Hoshi Spray Rose",
"Princess Kaori",
"Princess Kishi",
"Princess Maya",
"Princess Meiko",
"Princess Midori Spray",
"Princess Miyuki",
"Princess Pinku Spray",
"Princess Sakura",
"Princess Suki",
"Printempo",
"Prinze",
"Priority",
"Prism",
"Procerum African Tulip",
"Procut",
"Procut Horizon",
"Procut Lite",
"Procut Nite",
"Products",
"Prometeo",
"Promise",
"Proposal",
"Proud",
"Puffed Cotton",
"Pulse",
"Puma",
"Pumori",
"Pumpkin",
"Pumpkin Pie",
"Pumpkin Silver Tips",
"Pumpkin Tips",
"Pumpkin Wrap",
"Punjab",
"Punky Ball",
"Puppy",
"Pure Art",
"Pure Purple",
"Pureen",
"Purity",
"Purity Spray",
"Purity-Ausoblige",
"Purmori",
"Purpeta",
"Purpetta",
"Purple",
"Purple Accent",
"Purple Bat",
"Purple Cezanne",
"Purple Damascus",
"Purple Fiary",
"Purple Focal Scoop",
"Purple Haze",
"Purple Irischka",
"Purple Irishka",
"Purple Irishka-Sp",
"Purple Jean",
"Purple Jet",
"Purple Monster Focal Scoop",
"Purple Moon",
"Purple Passion",
"Purple Pixel",
"Purple Sky",
"Purple Spectro",
"Purple Spirit",
"Purple White Bicolor",
"Putumayo",
"Puzzle Sticks",
"Quartet Lavender",
"Quartet Red",
"Quartet Rose",
"Quartet White",
"Quartet Yellow",
"Quartz",
"Queen",
"Queen Anne Lace",
"Queen Annes Lace",
"Queen Berry",
"Queen Elizabeth",
"Queen Fish",
"Queen Mary",
"Queen Mayra",
"Queen Of Pearl",
"Queen Park",
"Queen Venus",
"Queen Victoria",
"Queenberry",
"Queenfish",
"Queens Crown",
"Queen'S Crown",
"Quick Sand",
"Quicksand",
"Rabane",
"Rachel",
"Radamel",
"Radiante",
"Rafaella",
"Ragazza",
"Ragusa",
"Rahmnus",
"Rainbow",
"Raising Pearl",
"Ramona",
"Randal",
"Ranja",
"Rap",
"Raspberry",
"Raspberry Ice",
"Raspberry Scoop",
"Raspemerald",
"Ravel",
"Raymond",
"Reagan",
"Reagan Amber",
"Reagan Bronze",
"Reagan Improved",
"Reagan Splendid",
"Reagan Sunny",
"Rebasco",
"Rebbeca",
"Rebecca",
"Record",
"Red",
"Red & White",
"Red Alert",
"Red And Blue Stripes",
"Red And Blue Tips",
"Red Apple Focal Scoop",
"Red Balance",
"Red Charm",
"Red Cherio",
"Red Color",
"Red Cooper",
"Red Copper",
"Red Corleone",
"Red Curtain Upright",
"Red Dawn",
"Red Delight",
"Red Emotion",
"Red Eye",
"Red Fantasy",
"Red Flame",
"Red Fox",
"Red Golden",
"Red Heart",
"Red Hero",
"Red Ice",
"Red Intuition",
"Red Light",
"Red Magic",
"Red Managua",
"Red Mikado",
"Red Monster",
"Red Oak",
"Red Ole",
"Red Panther",
"Red Paris",
"Red Passion",
"Red Passione",
"Red Piano",
"Red Pop Rosever",
"Red Sarah Bernhardt",
"Red Sox",
"Red Stone Hybrid",
"Red Symphony",
"Red Thalys",
"Red Tips",
"Red Tornado",
"Red Velvet",
"Red Velvet Focal Scoop",
"Red Velvet Scoop",
"Red Wanted",
"Reddish Purple",
"Redhill",
"Rediant",
"Redlight Romance",
"Redvolution",
"Regal",
"Regatta",
"Reliquary",
"Rembrandt",
"Remember",
"Remembrance",
"Renata",
"Rendezvouz",
"Rene Goscinny",
"Reno",
"Renoir",
"Resomme",
"Resource",
"Resplandor",
"Retro Collection",
"Retzia",
"Rex",
"Rex King",
"Rhamnus",
"Rhapsody",
"Rhodalite",
"Rhoslyn",
"Rialto",
"Ribbon",
"Ribbon Bronze",
"Rica",
"Richmond",
"Rihana",
"Rihanna",
"Ring Bearer",
"Rio Negro",
"Rise N Sun",
"Rising Sun",
"Ritomo",
"River Hybrid",
"Riviera",
"Rizo",
"Roast Baby Carrots",
"Roast Turkey",
"Robalini",
"Robellini Palm",
"Robina",
"Rocio",
"Rock",
"Rock Fire",
"Rock Star",
"Rocky Romance",
"Rocky Romance Spray",
"Rocky Wine",
"Rodas",
"Roger Rabbitt",
"Rojo",
"Romance",
"Romance Courchevel",
"Romance Hydra",
"Romance Loubeyres",
"Romance Maritime",
"Romance Nimes",
"Romance Nohant",
"Romance Peach",
"Romance Perigord",
"Romance Purple",
"Romance White",
"Romancero",
"Romantic Antike",
"Romantic Glory",
"Romantica Folies",
"Romany",
"Rome",
"Romina",
"Ronnie Orange",
"Rony",
"Roryal Explorer",
"Rosa Chario",
"Rosa Chiaro",
"Rosa Loves Me",
"Rosadita",
"Rosalind",
"Rosanella Spray",
"Rosano Elizabeth",
"Rosano Orange",
"Rose",
"Rose Alabaster",
"Rose Berry",
"Rose Dozen",
"Rose Dozen Bouquet",
"Rose Magic",
"Rose Painted Dozencb",
"Rose Single Stem",
"Rose/Garden Bouquet",
"Roseberry",
"Roselily",
"Roselily Anouska",
"Roselily Isabela",
"Roselily Isabella Double",
"Roselily Surprise Double",
"Rosemary",
"Rosenda",
"Rosetta",
"Rosette",
"Rosever",
"Rosever Green",
"Rosever Orange",
"Rosever Vintage",
"Roshlyn",
"Rosi Cheeks Scoop",
"Rosita",
"Rosita Vendela",
"Rossano",
"Rossano Charlotte",
"Rossano Elizabeth",
"Rossano Orange",
"Rossette",
"Rossini",
"Rossonero",
"Rouge",
"Rover",
"Roxanne",
"Royal",
"Royal Candyshop",
"Royal Explorer",
"Royal Flash",
"Royal Jazz",
"Royal Porcelina",
"Royal Princess",
"Royal Sunset",
"Royal Trinity",
"Royal Valentine",
"Royal Velvet 4 Blooms",
"Royal Victorian Box",
"Royal Virgin",
"Rubby",
"Rubi",
"Rubicom",
"Rubicon",
"Rubinho",
"Ruble",
"Ruby",
"Ruby Bijoux",
"Ruby Glitz",
"Ruby Globe",
"Ruby Sensation",
"Rubylite",
"Rudolph",
"Ruffle",
"Rumba",
"Ruscus",
"Ruscus Bleached",
"Ruscus Israeli",
"Ruscus Italian",
"Ruscus Tinted",
"Ruscus Tinted And Glittered",
"S. Trendy Tessino",
"Sabrina",
"Sacha",
"Sacramento",
"Safari",
"Safari Sunset",
"Saffina",
"Safflower",
"Saffron",
"Safi",
"Safina",
"Safora",
"Safora Oshi",
"Safran",
"Saga",
"Sage",
"Sago Palm",
"Sahara",
"Sahara Rosever",
"Sahara Sensation",
"Sahara Sensation Spray",
"Saigon",
"Saily",
"Saint Nicholas",
"Salal",
"Salignum Xanthoconus",
"Salinero Spray",
"Salma",
"Salmanasar",
"Salmanazar",
"Salmon Classic",
"Salmon Saucer",
"Saloniki",
"Saloon",
"Salvador",
"Samantha",
"Samarcanda",
"Samba",
"Samba Pa Ti",
"Sambuca",
"Sample",
"Samuela",
"Samurai",
"Sand Castle",
"Sandy",
"Sandy & Danny",
"Sandy Beauty",
"Sandy Femma",
"Sanoli",
"Santa Fe",
"Santafe",
"Santana",
"Santander",
"Santas Helper",
"Santorini",
"Santos",
"Saona",
"Sapporo",
"Sara",
"Sarah Bernhardt",
"Sarah'S Delight Helix Hybrid",
"Saronno",
"Sassafras",
"Satina",
"Satisfaction",
"Saturnus",
"Sauron",
"Savanna",
"Scabiosa Pods",
"Scandal",
"Scansano",
"Scarecrow",
"Scarlatta",
"Scarlatte",
"Scarlet",
"Scarlet Mimi",
"Scarlet Red",
"Scarlett Mini",
"Scarlette",
"Scarlette Plus",
"Schwarzwalder",
"Scipione",
"Scoop",
"Scoop Bon Bon Vanilla",
"Scoop Lilac",
"Scoops",
"Scoops Cherry Vanilla",
"Scooter",
"Scorpion",
"Sea Blue",
"Sea Prism",
"Sea Star Fern",
"Sea Waltz",
"Seasonal Color Bulk",
"Seattle",
"Secret Garden",
"Segreto",
"Sei Rewind",
"Sei Ribeus",
"Select Mix",
"Selene",
"Selfie",
"Selflove",
"Selva",
"Selva Romance",
"Senlitsu",
"Senna",
"Senorita",
"Senorita Pink",
"Sensation",
"Sensation White",
"Sensy",
"Sensy Pink",
"Senthyna",
"Senti Intensity",
"Sentiments Rose Bouquet 15 Stem",
"Sentyna",
"Sepia Thrill",
"Serenade",
"Serrada",
"Serrano",
"Serviceberry",
"Seville",
"Sex Bomb",
"Sexy Pink",
"Sexy Red",
"Seychelles",
"Shabby Chic",
"Shades Of Green Rose Bouquet",
"Shades Of Orange Rose Bouquet",
"Shades Of Pink Rose Bouquet",
"Shades Of Purple Rose Bouquet",
"Shades Of Red Rose Bouquet",
"Shades Of Yellow Rose Bouquet",
"Shadow Dancin' Trio Rose",
"Shakira",
"Shamira",
"Shampoo Ginger",
"Shamrock",
"Shaony",
"Sharon",
"Shilabe",
"Shimla",
"Shimmer",
"Shimmer Sister",
"Shimmering Rose",
"Shine On",
"Shiney Romance",
"Shining Star",
"Shiny Art",
"Shirley Temple",
"Shock",
"Shocking",
"Shocking Blue",
"Shocking Versilia",
"Shogun",
"Shooting Stars",
"Show",
"Show Girl",
"Show Time",
"Showbizz",
"Shrek",
"Shukrani",
"Shy",
"Sianna",
"Siberia",
"Sicilia!",
"Sideral",
"Siente",
"Silantoi",
"Silent",
"Silver",
"Silver Bell",
"Silver Brunia",
"Silver Cloud",
"Silver Dollar",
"Silver Dynamite",
"Silver Light",
"Silver Mikado",
"Silver Sand",
"Silver Shadow",
"Silverlight",
"Silverose",
"Silverstone",
"Silvery Light",
"Silvie",
"Simba",
"Simplon",
"Sinai",
"Sinclair",
"Sinderland",
"Sinensis",
"Sinensis Eversun",
"Sinensis Macarrone",
"Single",
"Single Carnation",
"Single Rose",
"Single Rose Bouquet",
"Sinzil Lilae",
"Sirasi",
"Sisto",
"Skies Tinted",
"Sky Blue",
"Sky Blue Mint",
"Sky Hybrid",
"Sky Pink",
"Sky Prism",
"Sky Walker",
"Sky Waltz",
"Skydiver",
"Skyfire",
"Skyler",
"Skyler Blue",
"Skyler Pink",
"Skyler Purple",
"Skyler White",
"Skylie",
"Skylight",
"Skyline",
"Smart",
"Smart Artist",
"Smart Caya",
"Smart June",
"Smart Luna",
"Smart Mix",
"Smart Navy",
"Smart Roswitha",
"Smash",
"Smilax",
"Smilax # 10",
"Smiley Sunday",
"Smoke Bush",
"Smoothie",
"Snow Bliss",
"Snow Blizz",
"Snow Bubbles",
"Snow Cap",
"Snow Dance",
"Snow Flake",
"Snow Frost",
"Snow Raspberry",
"Snow Storm",
"Snow White",
"Snowball",
"Snowball Gyp",
"Snowflake",
"Snowprince",
"Snowy Jewel",
"Sobi",
"Soft",
"Soft Pink Folies",
"Soft Scoop",
"Soho",
"Sol",
"Sola",
"Solair",
"Solange",
"Solano",
"Soleada",
"Soleado",
"Solei",
"Solemio",
"Solero Art",
"Solex",
"Solidago",
"Solidago Tinted",
"Solomio",
"Solomio Amos",
"Solomio Ard",
"Solomio Berni",
"Solomio Bono",
"Solomio Boyd",
"Solomio Cas",
"Solomio Clown Novelty",
"Solomio Cris",
"Solomio Edo",
"Solomio Esli",
"Solomio Gil",
"Solomio Gio",
"Solomio Imre",
"Solomio Lilliput Snow",
"Solomio Star Snow Tessino",
"Solomio Tino",
"Solomio White",
"Solomiotrendy Tessino",
"Somerset",
"Somerset!",
"Sonata",
"Sonatina",
"Song Of India",
"Sonia",
"Sonora",
"Sonrisa",
"Sonsoles",
"Sophie",
"Sorbet Berry",
"Sorbeto",
"Sorbetto",
"Sorbone",
"Sorbonne",
"Sorpresa",
"Soul",
"Soulmate",
"Sound",
"Souvenir",
"Sox",
"Spark",
"Spark White",
"Spark Yellow",
"Special Asst",
"Special Bride",
"Spectra",
"Spectro",
"Spell",
"Calafuria Sunny",
"Center Tips Xmas",
"Dark Tiana",
"Delistar",
"La Mira",
"Marcela",
"Megatron",
"Mistical",
"Pink Ray",
"Seldis",
"Spiral",
"Spiral Green Red",
"Spiral Red White",
"Splas Xmas",
"Spooky",
"Super Anastasia",
"Tamarindo",
"Tierra",
"Tri Xmas",
"Webb",
"White With Red Center",
"Yazoo",
"Spinelli",
"Spirit",
"Spitfire",
"Splendid",
"Splendor",
"Splendy",
"Spontini",
"Spookey",
"Spray",
"Blanche",
"Just Peachy",
"Planet",
"Princess Fairy Kiss",
"Sunshine",
"Wedding Romantica",
"Sprayed (Looks Natural)",
"Sprengeri",
"Spring Awakening",
"Spring Sky",
"Spring Time Collection",
"Sprit",
"Spritz",
"Spritz Sport Blanco Rosa",
"Squash",
"St Patricks Festivity",
"St. Patrick",
"Stamp",
"Stand By Me",
"Star",
"Star 2000",
"Star Anice",
"Star Barista",
"Star Blush",
"Star Cherry",
"Star Fighter",
"Star Frutty",
"Star Hot Pink",
"Star Platinum",
"Star Ruby",
"Star Snow White",
"Star Spangled Banner",
"Star Violet",
"Star Walk",
"Star Walker",
"Starblush",
"Stardust",
"Starfighter",
"Starfire",
"Starfish",
"Stargate",
"Stargazer",
"Starlight",
"Starry Nebula",
"Steel Grass",
"Stellate",
"Stelle",
"Stephanie",
"Sterling",
"Stick Assembly",
"Stiletto",
"Still Loving You",
"Stock Single",
"Stone",
"Stox Rose Pink",
"Stox White",
"Stox Yellow",
"Stratus",
"Stratuss",
"Strauss",
"Strawberry",
"Strawberry Blush",
"Strawberry Hoop Scoop",
"Strawberry Natural",
"Strawberry Scoop",
"Strawberry Yellow",
"Striato",
"Stripy",
"Stunning",
"Sublime",
"Success",
"Success Cloni Favola",
"Success Nerone",
"Success Sherry",
"Success Venere",
"Succession",
"Sugar 5 Stem",
"Sugar Doll",
"Sugar Kisses 6 Stem",
"Sugilite",
"Suglite",
"Sulpice",
"Sumac",
"Sumatra",
"Summer Crush",
"Summer Lovin",
"Summer Sun",
"Summer Vibes Box",
"Summerlight",
"Summerset",
"Sun Bird",
"Sun City",
"Sun Club",
"Sunagua",
"Sunbright",
"Suncica",
"Suncity",
"Sunderland",
"Sunflame",
"Sunflower - Vincent Choice",
"Sunflowers",
"Sunkiss",
"Sunmaster",
"Sunny Art",
"Sunny Ball",
"Sunny Day",
"Sunny Guajira",
"Sunny Komachi",
"Sunny Lady",
"Sunny Rebecca",
"Sunny Zembla",
"Sunplum",
"Sunrich Gold",
"Sunrich Orange",
"Sunrise",
"Sunset",
"Sunset Expression",
"Sunset Glory",
"Sunset Xpression",
"Sunspring",
"Suntane",
"Supe Silvie",
"Super",
"Super 2 Combo",
"Super 8",
"Super Burgundy",
"Super Designer Bouquet 25 Stem",
"Super Designer Rose",
"Super Freedom",
"Super Green",
"Super Magnum",
"Super Mix",
"Super Nova",
"Super Orange",
"Super Salmon",
"Super Silvie",
"Super Star",
"Super Sun",
"Super Wow",
"Supernova",
"Superstar",
"Superstition",
"Supplies",
"Supreme",
"Suri",
"Surprise Double",
"Susara",
"Suspiro",
"Sussara",
"Sutan",
"Swan",
"Swan Lake",
"Swansea",
"Sweet",
"Sweet 4 Love",
"Sweet Akito",
"Sweet Art",
"Sweet Avalanche",
"Sweet Blossom",
"Sweet Cake",
"Sweet Collection",
"Sweet Coral",
"Sweet Dolomiti",
"Sweet Dream",
"Sweet Elegance",
"Sweet Escimo",
"Sweet Eye",
"Sweet Flow Spray",
"Sweet Gum",
"Sweet Heart",
"Sweet Heart Lemoncello",
"Sweet Heart Porcelina",
"Sweet Life",
"Sweet Mama",
"Sweet Memory",
"Sweet Passion",
"Sweet Pea",
"Sweet Perfumella",
"Sweet Potato",
"Sweet Princess",
"Sweet Romance",
"Sweet Rose",
"Sweet Sara",
"Sweet Scoop",
"Sweet Sensation",
"Sweet Sixteen",
"Sweet Sugar",
"Sweet Unique",
"Sweet Valley",
"Sweet William White",
"Sweet Williams",
"Sweet Zanica",
"Sweetberry",
"Sweetest Impression",
"Sweetness",
"Swing",
"Sword Fern",
"Syberia",
"Sylvan",
"Sylver",
"Sylvia",
"Sylvie",
"Symbol",
"Symphony",
"Tabasco",
"Tabatha",
"Table Dance",
"Tabor",
"Tachini",
"Tairona",
"Take My Breath Away",
"Talea",
"Tali",
"Tampa",
"Tanaga!",
"Tanana",
"Tangelo",
"Tango",
"Tango Art Orange",
"Tango Pink Brush",
"Tanoshi",
"Tara",
"Tarapaca",
"Tara-Solidago",
"Targaryen",
"Tarifa",
"Tarrango",
"Tarufi",
"Tattoo",
"Taurus",
"Tavor Double",
"Tavor Lemon",
"Taxo",
"Tayrona",
"Tecolote Cafe",
"Tecolote Sunset",
"Tedcha",
"Tee Pee Palm",
"Teenager",
"Teide",
"Telstar",
"Temptation",
"Tenderly",
"Tenerife",
"Tequila Sunrise",
"Termoli",
"Terra Mocca",
"Terra Pink",
"Terracota",
"Terracota Caramel",
"Terrango",
"Tess",
"Tess - Ausyacht",
"Tessino",
"Test",
"Testarosa",
"Testarossa",
"Thalissa",
"Thalys",
"The Edge",
"Thea",
"Thia",
"Think Pink",
"Thirza",
"Thistle",
"Thrill Box",
"Thumper",
"Thunderbolt",
"Thyrsoide",
"Thyrsoides",
"Ti Leaf",
"Ti Leaf Red",
"Ti Leaves",
"Tiana",
"Tiber",
"Tibet",
"Tico Tico Pink",
"Tie Dye",
"Tie Dye Rainbow",
"Tiepolo",
"Tiepolo Fuchsia",
"Tiepolo Fucsia",
"Tiepolo Viola",
"Tiffany",
"Tiger",
"Tigger",
"Tigris",
"Timana",
"Timber",
"Timoko",
"Tina",
"Tintipan",
"Tinto",
"Tiopolo Fucsia",
"Tiramisu",
"Tirreno",
"Tisento",
"Tissue Culture",
"Titanic",
"Tobacco",
"Toff",
"Toffee",
"Tokay",
"Tokio",
"Tokyo",
"Toledo",
"Tolima",
"Tonatiuh",
"Top Dollar",
"Top Secret",
"Topaz",
"Topsin",
"Tormenta",
"Tornado",
"Tornado Red",
"Toscana",
"Toscanini",
"Totem",
"Totumo",
"Touch Of Class",
"Toulouse Lautrec",
"Tourmaline",
"Tower Chamois",
"Tracy",
"Trebbiano",
"Trebol",
"Tree Fern",
"Trendy Tessino",
"Tres Chic",
"Tresor",
"Tressor",
"Trevi",
"Trick Or Thorn Collection",
"Trick Or Treat",
"Trigreen",
"Trigreen Ball Green",
"Trinity",
"Trio",
"Trissia",
"Triton",
"Triton Blue",
"Triton White",
"Triumph",
"Trix Rabbit",
"Tropic Crush",
"Tropic Diamond",
"Tropical",
"Tropical Amazon",
"Tropical Amazone",
"Tropical Crush",
"Tropical Diamond",
"Tropical Paradise",
"Trottola",
"Trotum",
"Trotum Female",
"TRUE",
"True Colors",
"True Love",
"True Romance",
"True Romance Spray",
"Trueno",
"Trump",
"Trumpet",
"Trumpet Candy Club",
"Trumpet Ferrero",
"Trumpet Flashpoint",
"Trumpet Outback",
"Trumpet Profundo",
"Trumpet Serrano",
"Trumpet Table Dance",
"Trumpet Tarrango",
"Trumpet Touchstone",
"Trumpet Valverde",
"Trumpet Zambesi",
"Trust",
"Tsumugi",
"Tukano",
"Tundra",
"Tuparro",
"Turtle",
"Tusca",
"Tutti Frutti",
"Twilight",
"Twin",
"Twinkle Bride",
"Twister",
"Tycon",
"Tycoon",
"Typhoon",
"Uchuva",
"Umbrella Fern",
"Uncle Sam",
"Unconditional",
"Undercover",
"Unforgiven",
"Unica",
"Unicorn Kisses",
"Union",
"Unique",
"Universe",
"Upright",
"Upright Hot Biscuit",
"Uva",
"Uvalux",
"V.I.Pink",
"Vagnilia Striato",
"Valencia Sensation",
"Valentina",
"Valentine 8 Stem",
"Valentine Rose Bouquet",
"Valentine Song Collection",
"Valentino",
"Valeska",
"Value Bunch",
"Valverde",
"Van Gogh",
"Vancouver",
"Vangelis",
"Vani",
"Vanilla",
"Vanilla Scoop",
"Vanilla Sorbet",
"Vanilla White",
"Vanity Fair Applause",
"Vannia",
"Variegated",
"Vasanta",
"V-Day Color Mix",
"Vday Colors",
"Vega",
"Veggie",
"Veld Fire",
"Velluto",
"Velvet",
"Velvet Lace",
"Velvet Queen",
"Velvet Red",
"Velvet Wings",
"Vendela",
"Vendela/Playa Blanca",
"Vendome",
"Venice",
"Ventura",
"Venturoso",
"Venus",
"Vera",
"Verdi",
"Vermeer",
"Vero",
"Verona",
"Veronica",
"Veronica Pink",
"Veronica Salmon",
"Versaille",
"Versilia",
"Versilla",
"Vespa",
"Vestaro",
"Vesuvio",
"Vesuvio Tangy",
"Vi Pink",
"Viana",
"Vibrant Dozen Rose",
"Viburnum",
"Vicent Choice",
"Vicent Fresh",
"Vicky",
"Victoria",
"Victorian Amelily",
"Victorian Bianca",
"Victorian Gia",
"Victorian Manuela",
"Victorian Maria Pia",
"Victorian Precious Moments",
"Victorian Spirit Of Victory",
"Victory",
"Vinca",
"Vincent Choice",
"Vincent Fresh",
"Vincent'S Choice",
"Vincent'S Fresh",
"Vino Bianco",
"Vintage",
"Vintage Almond",
"Vintage Candy",
"Vintage Paloma",
"Vintage Rose",
"Viola",
"Violet",
"Violet Hill",
"Violette",
"Viper Wine",
"Virgilio",
"Virginia",
"Virginia Red",
"Vitality",
"Vitamin C",
"Vitamina C",
"Viva",
"Vivaro",
"Viviane",
"Vladimir",
"Vodoo",
"Vogue",
"Voicemail",
"Volans",
"Volare",
"Volcano",
"Volkerfrieden",
"Voodoo",
"Voragine",
"Vortex",
"Voyage",
"Voyager",
"Vuvuzela",
"Vuvuzela Romantica",
"Vybowl",
"Vyking",
"Wabara",
"Wabara Aoi Fuga Spray",
"Wabara Joli Spray",
"Wabara Loli Spray",
"Wabara Miyabi",
"Wabara Sola Spray",
"Walker",
"Waltz Series",
"Wanted",
"Wasabi",
"Washington",
"Watergame",
"Waxflower Purple",
"Wedding",
"Wedding Blossom",
"Wedding Collection",
"Wedding Kiss",
"Wedding Pink",
"Wedding Planner",
"Wedding Rosever",
"Wedding Rosever Pink Spray",
"Wedding Sensation",
"Wedding Spirit",
"Wedding X-Pression",
"Westminster Abbey",
"What A Feeling",
"Whatsapp",
"Whipped Cream",
"Whisper",
"Whistler",
"White",
"White And Blue",
"White And Red",
"White Art",
"White Beauty",
"White Chocolate",
"White Cloud",
"White Cup",
"White Diamond",
"White Dove",
"White Ever",
"White Flirt",
"White Focal Scoop",
"White Galaxy",
"White Glitter",
"White Golden",
"White Green Tinted",
"White Ideal",
"White Komachi",
"White Magnum",
"White Majolica",
"White Majolika",
"White Mikado",
"White Nite",
"White O'Hara",
"White Panda",
"White Piano",
"White Porcelain",
"White Princess",
"White Prom",
"White Quartz",
"White Red Blue",
"White Shimmer",
"White Sound",
"White Spear",
"White Spray",
"White Star",
"White Swan",
"White With Red Outer Petals",
"Whitehorse",
"Whitney",
"Wht Majolica",
"Wild",
"Wild Berry",
"Wild Bourdeaux",
"Wild Cat",
"Wild Crown",
"Wild Esperance",
"Wild Fuji",
"Wild Jamaica",
"Wild Modena",
"Wild Napoli",
"Wild Natalya",
"Wild Pear",
"Wild Primadonna",
"Wild Radish",
"Wild Romance",
"Wild Sperance",
"Wild Spirit",
"Wild Tampa",
"Wild Thrill",
"Wild Topaz",
"Wild Whistler",
"Wimbledon",
"Winbledon",
"Windsong",
"Windsor",
"Wine Cover",
"Winner Thrill",
"Winter Enhanced",
"Winterfell",
"Wiseman",
"Witch",
"With Silver Glitter",
"Wizard",
"Woodstar",
"Wow",
"Wreath",
"Xanadu",
"Xanthe",
"X-Citing",
"Xentina",
"X-Factor",
"Xlence",
"Xlence Cb",
"Xlence Glitter",
"Xlence Tinted",
"Xlence Tinted & Glittered",
"X-Mas",
"Xmas Bulb",
"Xmas Festivity",
"Xmas Green And Red Sparkles",
"X-Mas Splash",
"Xmas Star",
"Xmas Tree",
"Xochi",
"Yale",
"Yamato",
"Yarrow",
"Yarrow Parker",
"Yashika",
"Yellow",
"Yellow & Red Spray Rose",
"Yellow Babe",
"Yellow Brush",
"Yellow Center",
"Yellow Champagne",
"Yellow Coral",
"Yellow Crush",
"Yellow Diamond",
"Yellow King",
"Yellow Merengue",
"Yellow Moon",
"Yellow Pavia",
"Yellow Poplar",
"Yellow Strike",
"Yellow Timeless",
"Yellow Viana",
"Yelloween",
"Yellowstone",
"Yellowstone Orange",
"Yerevan",
"Yerseke",
"Yin Yang",
"Ying Yang",
"Yoder Fox",
"Yoder Mist",
"Yoko Ono",
"Yokohama",
"Yoru",
"You Make My Dreams",
"Younique",
"Yukari Cherry",
"Yukari Light",
"Yukari Light Cherry",
"Yukari Scuro",
"Yves Piaget",
"Zafira -Bb",
"Zafiro",
"Zambesi",
"Zanella",
"Zanica",
"Zanzibar",
"Zazu",
"Zelmira",
"Zembla",
"Zembla Cream",
"Zembla Lime",
"Zembla Sunny",
"Zenit",
"Zenith",
"Zepellin",
"Zephir",
"Zeppelin",
"Ziggy",
"Zinta",
"Zip",
"Zip White",
"Zircon",
"Zorro",
"Zulu",
"Zumba",
"Zurigo"
];


// Modal HTML to add to the page
const modalHTML = `
<div id="productAddModal" style="display: none; position: fixed; z-index: 10; left: 0; top: 0; width: 100%; height: 100%; overflow: auto; background-color: rgb(0,0,0); background-color: rgba(0,0,0,0.4); padding-top: 60px;">
  <div style="background-color: #fefefe; margin: 5% auto; padding: 20px; border: 1px solid #888; width: 30%; position: relative;">
    <div id="closeButton" style="position: absolute; top: 10px; right: 15px; font-size: 24px; font-weight: bold; cursor: pointer;">
        &times;
    </div>
    <div style="margin-bottom: 15px;">
      <label for="categoryInput">Category:</label>
      <input type="text" id="categoryInput" name="category">
    </div>
    <div style="margin-bottom: 15px;">
      <label for="colorInput">Color:</label>
      <input type="text" id="colorInput" name="color">
    </div>
    <div style="margin-bottom: 15px;">
      <label for="varietyInput">Variety:</label>
      <input type="text" id="varietyInput" name="variety">
    </div>
    <div style="margin-bottom: 15px;">
      <label for="gradeInput">Grade:</label>
      <input type="text" id="gradeInput" name="grade">
    </div>
    <div style="margin-bottom: 15px;">
      <label for="codeInput">Code:</label>
      <input type="text" id="codeInput" name="code">
    </div>
    <button id="enterButton">Enter</button>
  </div>
</div>
`;
document.body.insertAdjacentHTML('beforeend', modalHTML);


//function to remove matches from vendor product string as they are found
function removeMatchFromString(originalString, match) {
    let pattern = new RegExp(`\\b${match}\\b`, 'i'); // Using word boundaries to match whole words
    return originalString.replace(pattern, '').trim();
}

//function for consistent capitalization
function toTitleCase(str) {
    return str.replace(/\w\S*/g, function (txt) {
        return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
    });
}

// Function to find the best match or a partial match from vendor product string to populate fields with
function findBestMatch(array, searchString) {
    let match = '';
    let partialMatch = '';
    let lowerSearchString = searchString.toLowerCase();
    let wordsInSearchString = lowerSearchString.split(/\s+/);

    array.forEach(item => {
        let lowerItem = item.toLowerCase();
        if (lowerSearchString.includes(lowerItem) && lowerItem.length > match.length) {
            match = item;
        } else {
            // Find a partial match where the substring must be at least half the length of the item
            wordsInSearchString.forEach(substring => {
                if (lowerItem.startsWith(substring) && substring.length >= lowerItem.length / 2 && substring.length > partialMatch.length) {
                    partialMatch = item;
                }
            });
        }
    });

    return match || partialMatch; // Return full match or the best partial match
}


function showModal(event) {

    window.currentActiveButton = event.target; // Store the reference to the clicked button

    let vendorProductString = event.target.closest('tr').cells[11].textContent.toLowerCase();

    let extractedValues = {};

    // Find the best match for each field and update the vendorProductString
    extractedValues.category = findBestMatch(category, vendorProductString);
    vendorProductString = removeMatchFromString(vendorProductString, extractedValues.category);

    extractedValues.color = findBestMatch(color, vendorProductString);
    vendorProductString = removeMatchFromString(vendorProductString, extractedValues.color);

    extractedValues.variety = findBestMatch(variety, vendorProductString);
    vendorProductString = removeMatchFromString(vendorProductString, extractedValues.variety);

    extractedValues.grade = findBestMatch(grade, vendorProductString);
    vendorProductString = removeMatchFromString(vendorProductString, extractedValues.grade);

    // If any field is still empty, use the first word from the remaining string
    let remainingWords = vendorProductString.split(/\s+/);
    Object.keys(extractedValues).forEach(field => {
        if (!extractedValues[field] && remainingWords.length > 0) {
            extractedValues[field] = remainingWords.shift(); // Assign the first word to the field
        }
    });

    // Set the values of the modal's input fields, apply formatting
    document.querySelector("#categoryInput").value = toTitleCase(extractedValues.category || "");
    document.querySelector("#colorInput").value = toTitleCase(extractedValues.color || "");
    document.querySelector("#varietyInput").value = toTitleCase(extractedValues.variety || "");
    document.querySelector("#gradeInput").value = toTitleCase(extractedValues.grade || "");

    // Code field generation logic
    const codeValue = (extractedValues.category ? extractedValues.category.substring(0, 4) : '') +
        (extractedValues.color ? extractedValues.color.substring(0, 3) : '');
    document.querySelector("#codeInput").value = codeValue.toUpperCase();

    // Display the modal
    document.querySelector("#productAddModal").style.display = "block";

    //focus on first field of modal for keyboard navigation
    document.querySelector("#categoryInput").focus();

}


function hideModal() {
    document.querySelector("#productAddModal").style.display = "none";
    
    if (window.currentActiveButton) {
        // Find the parent row of the button that opened the modal
        let parentRow = window.currentActiveButton.closest('tr');
        // Focus on the input element in the cell before the cell containing the button
        let targetInput = parentRow.cells[14].querySelector('input');
        if (targetInput) {
            targetInput.focus();
        }
    }
}

// Function to collect data and create JSON object, then send json object in API call
function collectDataAndCreateJSON() {
    const category = document.querySelector("#categoryInput").value;
    const color = document.querySelector("#colorInput").value;
    const variety = document.querySelector("#varietyInput").value;
    const grade = document.querySelector("#gradeInput").value;
    const code = document.querySelector("#codeInput").value;

    const productData = {
        category,
        color,
        variety,
        grade,
        code
    };

    console.log("Collected data:", productData);

    // Retrieve the API token from chrome.storage and use it in the POST request
    chrome.storage.sync.get('token', function (data) {
        const token = data.token;
        productData.authenticationToken = token
        const requestOptions = {
            method: 'POST',
            headers: {
                Accept: "application/json",
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(productData),
        };

        // Send post request to local python server, which acts as a proxy to the API
        //Komet's CORS policy prevents sending requests to the api from the frontend, this is a workaround for that
        fetch('http://localhost:5000/api/product/add', requestOptions)
            .then(response => response.json())
            .then(data => chrome.runtime.sendMessage({ action: "showNotification", title: "Komet Item Update", message: data.message }))
            .catch(error => console.error('Error:', error));
    });
    hideModal();
}

// Add event listener to the Enter button in the modal
document.querySelector("#enterButton").addEventListener("click", collectDataAndCreateJSON);

// Add click event listener for the close button
document.querySelector("#closeButton").addEventListener("click", hideModal);

// Add buttons to each row in the table
let table = document.querySelector("#grid-vendor-availability-staging");

function waitForElementAndExecute(selector, callback) {
    const element = document.querySelector(selector);

    if (element.rows[1]) {
        console.log(element)
        console.log('Element found', selector);
        callback(element);
    } else {
        console.log('Element not found, waiting for it...', selector);
        setTimeout(waitForElementAndExecute.bind(null, selector, callback), 500); // Check again in 500 ms
    }
}
//add cells to table, and shift the following cells one cell to right
function addCells() {
    console.log('adding cells')
    for (let i = 0; i < table.rows.length; i++) {

        if (i == 0) {
            let table = document.querySelector('.ui-jqgrid-htable')
            let cell1 = table.rows[0].cells[15];
            cell1.textContent = 'Add Product'
            let cell2 = table.rows[0].cells[16];
            cell2.textContent = 'Vendor'
            let cell3 = table.rows[0].cells[17];
            cell3.textContent = 'Available From'
            let cell4 = table.rows[0].cells[18];
            cell4.textContent = 'Quantity'
            let cell5 = table.rows[0].cells[19];
            cell5.textContent = 'St/Bun'
            continue;
        };

        let cell = table.rows[i].insertCell(15);
        cell.style.textAlign = 'center';
        let button = document.createElement('button');
        button.textContent = '+';
        button.addEventListener('click', function (event) {
            showModal(event); // Pass the click event to the showModal function
        });
        cell.appendChild(button);
    }
}

waitForElementAndExecute('#grid-vendor-availability-staging', addCells);

chrome.runtime.onMessage.addListener(
    function (request, sender, sendResponse) {
        if (request.action === "addColumn") {
            console.log("Message received in content script to add a column.");
            waitForElementAndExecute('#grid-vendor-availability-staging', addCells);
        }
    }
);

function checkAndAddCells() {
    // Assuming you have a way to select the specific column, for example, the 16th column (index 15)
    const rows = document.querySelector("#grid-vendor-availability-staging").rows;
    const cellValue = rows[1].cells[15]?.textContent; // Change 15 to the actual index of your column
    if (cellValue !== '+') {
        addCells()
    }

}

// Run the check every 3 seconds
setInterval(checkAndAddCells, 3000);

